//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 10:01:47 AM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.GEN0015;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.sspb.recebimento.ConteudoMsgRecebida;

/**
 * <p>
 * Java class for GEN0015ComplexType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GEN0015ComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodMsg" type="{http://www.bcb.gov.br/GEN/GEN0015.xsd}CodMsg"/>
 *         &lt;element name="ISPBEmissor" type="{http://www.bcb.gov.br/GEN/GEN0015.xsd}ISPB"/>
 *         &lt;element name="ISPBDestinatario" type="{http://www.bcb.gov.br/GEN/GEN0015.xsd}ISPB"/>
 *         &lt;element name="NumCtrlIF" type="{http://www.bcb.gov.br/GEN/GEN0015.xsd}ControleIF"/>
 *         &lt;element name="NumCtrlReqIFOr" type="{http://www.bcb.gov.br/GEN/GEN0015.xsd}ControleIF" minOccurs="0"/>
 *         &lt;element name="TpTransm" type="{http://www.bcb.gov.br/GEN/GEN0015.xsd}TpTransm"/>
 *         &lt;element name="NomArq" type="{http://www.bcb.gov.br/GEN/GEN0015.xsd}Nome"/>
 *         &lt;element name="IdentdArq" type="{http://www.bcb.gov.br/GEN/GEN0015.xsd}IdentdArq" minOccurs="0"/>
 *         &lt;element name="TamArq" type="{http://www.bcb.gov.br/GEN/GEN0015.xsd}TamArq" minOccurs="0"/>
 *         &lt;element name="CodHash" type="{http://www.bcb.gov.br/GEN/GEN0015.xsd}CodHash" minOccurs="0"/>
 *         &lt;element name="Hist" type="{http://www.bcb.gov.br/GEN/GEN0015.xsd}Historico"/>
 *         &lt;element name="DtHrPart" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DtMovto" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GEN0015ComplexType", propOrder = { "codMsg", "ispbEmissor", "ispbDestinatario", "numCtrlIF", "numCtrlReqIFOr", "tpTransm", "nomArq", "identdArq", "tamArq",
        "codHash", "hist", "dtHrPart", "dtMovto" })
public class GEN0015ComplexType implements ConteudoMsgRecebida {

    @XmlElement(name = "CodMsg", required = true)
    private String codMsg;
    @XmlElement(name = "ISPBEmissor", required = true)
    private String ispbEmissor;
    @XmlElement(name = "ISPBDestinatario", required = true)
    private String ispbDestinatario;
    @XmlElement(name = "NumCtrlIF", required = true)
    private String numCtrlIF;
    @XmlElement(name = "NumCtrlReqIFOr")
    private String numCtrlReqIFOr;
    @XmlElement(name = "TpTransm", required = true)
    private String tpTransm;
    @XmlElement(name = "NomArq", required = true)
    private String nomArq;
    @XmlElement(name = "IdentdArq")
    private String identdArq;
    @XmlElement(name = "TamArq")
    private BigInteger tamArq;
    @XmlElement(name = "CodHash")
    private String codHash;
    @XmlElement(name = "Hist", required = true)
    private String hist;
    @XmlElement(name = "DtHrPart", required = true)
    @XmlSchemaType(name = "dateTime")
    private XMLGregorianCalendar dtHrPart;
    @XmlElement(name = "DtMovto", required = true)
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar dtMovto;

    /**
     * Gets the value of the codMsg property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCodMsg() {
        return codMsg;
    }

    /**
     * Sets the value of the codMsg property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCodMsg(String value) {
        this.codMsg = value;
    }

    /**
     * Gets the value of the ispbEmissor property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getISPBEmissor() {
        return ispbEmissor;
    }

    /**
     * Sets the value of the ispbEmissor property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setISPBEmissor(String value) {
        this.ispbEmissor = value;
    }

    /**
     * Gets the value of the ispbDestinatario property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getISPBDestinatario() {
        return ispbDestinatario;
    }

    /**
     * Sets the value of the ispbDestinatario property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setISPBDestinatario(String value) {
        this.ispbDestinatario = value;
    }

    /**
     * Gets the value of the numCtrlIF property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNumCtrlIF() {
        return numCtrlIF;
    }

    /**
     * Sets the value of the numCtrlIF property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNumCtrlIF(String value) {
        this.numCtrlIF = value;
    }

    /**
     * Gets the value of the numCtrlReqIFOr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNumCtrlReqIFOr() {
        return numCtrlReqIFOr;
    }

    /**
     * Sets the value of the numCtrlReqIFOr property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNumCtrlReqIFOr(String value) {
        this.numCtrlReqIFOr = value;
    }

    /**
     * Gets the value of the tpTransm property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTpTransm() {
        return tpTransm;
    }

    /**
     * Sets the value of the tpTransm property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTpTransm(String value) {
        this.tpTransm = value;
    }

    /**
     * Gets the value of the nomArq property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNomArq() {
        return nomArq;
    }

    /**
     * Sets the value of the nomArq property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNomArq(String value) {
        this.nomArq = value;
    }

    /**
     * Gets the value of the identdArq property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIdentdArq() {
        return identdArq;
    }

    /**
     * Sets the value of the identdArq property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIdentdArq(String value) {
        this.identdArq = value;
    }

    /**
     * Gets the value of the tamArq property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getTamArq() {
        return tamArq;
    }

    /**
     * Sets the value of the tamArq property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setTamArq(BigInteger value) {
        this.tamArq = value;
    }

    /**
     * Gets the value of the codHash property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCodHash() {
        return codHash;
    }

    /**
     * Sets the value of the codHash property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCodHash(String value) {
        this.codHash = value;
    }

    /**
     * Gets the value of the hist property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getHist() {
        return hist;
    }

    /**
     * Sets the value of the hist property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setHist(String value) {
        this.hist = value;
    }

    /**
     * Gets the value of the dtHrPart property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtHrPart() {
        return dtHrPart;
    }

    /**
     * Sets the value of the dtHrPart property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtHrPart(XMLGregorianCalendar value) {
        this.dtHrPart = value;
    }

    /**
     * Gets the value of the dtMovto property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtMovto() {
        return dtMovto;
    }

    /**
     * Sets the value of the dtMovto property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtMovto(XMLGregorianCalendar value) {
        this.dtMovto = value;
    }

    /*
     * (non-Javadoc)
     * 
     * @see br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.sspb.recebimento.ConteudoMsgRecebida#getIdMensagemOrigem()
     */
    public Long getIdMensagemOrigem() {
        return null;
    }

    /**
     * {@inheritDoc}
     * 
     * @see br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.sspb.recebimento.ConteudoMsgRecebida#getNumIdent()
     */
    public Long getNumIdent() {
        return null;
    }

    /*
     * (non-Javadoc)
     * 
     * @see br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.sspb.recebimento.ConteudoMsgRecebida#getNumCtrlDDA()
     */
    public String getNumCtrlDDA() {
        return null;
    }
}
