//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 09:22:20 AM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0005;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0005 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can
 * consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods
 * for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0005
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DDA0005ComplexType }
     * 
     */
    public DDA0005ComplexType createDDA0005ComplexType() {
        return new DDA0005ComplexType();
    }

    /**
     * Create an instance of {@link GrupoDDA0005AgrgdDDAComplexType }
     * 
     */
    public GrupoDDA0005AgrgdDDAComplexType createGrupoDDA0005AgrgdDDAComplexType() {
        return new GrupoDDA0005AgrgdDDAComplexType();
    }

    /**
     * Create an instance of {@link GrupoDDA0005CtCliPagdrComplexType }
     * 
     */
    public GrupoDDA0005CtCliPagdrComplexType createGrupoDDA0005CtCliPagdrComplexType() {
        return new GrupoDDA0005CtCliPagdrComplexType();
    }

    /**
     * Create an instance of {@link DDA0005R1ComplexType }
     * 
     */
    public DDA0005R1ComplexType createDDA0005R1ComplexType() {
        return new DDA0005R1ComplexType();
    }

}
