/**
 * Projeto:         Cobrança Bancária
 * Camada Projeto:  comum-ejb
 * Pacote:          br.com.sicoob.sisbr.sicoobdda.comum.negocio.enums
 * Arquivo:         PesquisaEnum.java
 * Data Criação:    24/09/2012
 */
package br.com.sicoob.sisbr.sicoobdda.comum.negocio.enums;

/**
 * PesquisaEnum é responsável por
 * 
 * @author Fabricio.Brandao
 */
public enum PesquisaEnum {
    HISTORICO_PAGINADA("PESQUISAR_HISTORICO", "OBTER_NUMERO_REGISTROS_PESQUISAR_HISTORICO"),
    BENEFICIARIO_GESTOR_NOME_PAGINADA("PESQUISAR_BENEFICIARIO_BY_NOME", "OBTER_NUMERO_REGISTROS_PESQUISAR_BENEFICIARIO_BY_NOME"),
    VALORES_POR_PERFIL_PAGINADA("PESQUISAR_VALORES_PERFIL", "OBTER_NUMERO_REGISTROS_VALOR_PERFIL"),
    PESQUISA_PERFIL_TARIFARIO("PESQUISAR_PERFIL_TARIFARIO", "OBTER_NUMERO_REGISTROS_PERFIL_TARIFARIO"),
    TABELA_BASICA_TARIFAS("PESQUISAR_TABELA_BASICA_TARIFAS", "OBTER_NUMERO_REGISTROS_PESQUISAR_TABELA_BASICA_TARIFAS"),
    PAGADOR_BENEFICIARIO("PESQUISAR_PAGADOR_BENEFICIARIO_PAGINADO", "OBTER_NUMERO_REGISTROS_PAGADOR_BENEFICIARIO"),
    PESQUISAR_PAGADORES_POR_GRUPO_DISTRIBUICAO("PESQUISAR_PAGADORES_POR_GRUPO_DISTRIBUICAO", "OBTER_NUMERO_REGISTROS_PAGADORES_POR_GD"),
    GRUPO_DISTRIBUICAO_BENEFICIARIO("PESQUISAR_GRUPO_DISTRIBUICAO_BENEFICIARIO_PAGINADO", "OBTER_NUMERO_REGISTROS_GRUPO_DISTRIBUICAO_BENEFICIARIO"),
    SACADOR_AVALISTA_BENEFICIARIO("PESQUISAR_SACADOR_AVALISTA_BENEFICIARIO_PAGINADO", "OBTER_NUMERO_REGISTROS_SACADOR_AVALISTA_BENEFICIARIO"),
    PESQUISAR_BENEFICIARIO_PAGINADO_VIEW("PESQUISAR_BENEFICIARIO_PAGINADO", "OBTER_PESQUISAR_BENEFICIARIO_PAGINADO"),
    PESQUISAR_BOLETOS_EMISSAO_2VIA("PESQUISAR_BOLETOS_EMISSAO_2VIA", "OBTER_PESQUISAR_BOLETOS_EMISSAO_2VIA"),
    PESQUISAR_GRADE_HORARIA("PESQUISAR_GRADE_HORARIA", "OBTER_QTD_GRADE_HORARIA"),
    PESQUISAR_SOLICITACAO_BOLETOS_PRE_IMPRESSO("PESQUISAR_SOLICITACAO_BOLETOS_PRE_IMPRESSO", "OBTER_PESQUISAR_SOLICITACAO_BOLETOS_PRE_IMPRESSO"),
    PESQUISAR_PAGADOR_PAGINADO("PESQUISAR_PAGADOR", "OBTER_NUMERO_REGISTROS_PESQUISAR_PAGADOR"),
    PESQUISAR_PAINEL_MONITORACAO("PESQUISAR_PAINEL_MONITORACAO", "OBTER_PESQUISAR_PAINEL_MONITORACAO"),
    PESQUISAR_COMANDO_BOLETO("PESQUISAR_COMANDO_BOLETO", "OBTER_PESQUISAR_COMANDO_BOLETO"),
    PESQUISAR_PAINEL_MONITORACAO_RETORNO("PESQUISAR_PAINEL_MONITORACAO_RETORNO", "OBTER_PESQUISAR_PAINEL_MONITORACAO_RETORNO"),
    PESQUISAR_SOLICITACAO_PROCESSAMENTO_BOLETO("PESQUISAR_SOLICITACAO_PROCESSAMENTO_BOLETO", "OBTER_PESQUISAR_SOLICITACAO_PROCESSAMENTO_BOLETO"),
    PESQUISAR_SOLICITACAO_PROCESSAMENTO_PAGADOR("PESQUISAR_SOLICITACAO_PROCESSAMENTO_PAGADOR", "OBTER_PESQUISAR_SOLICITACAO_PROCESSAMENTO_PAGADOR"),
    PESQUISAR_SOLICITACAO_PROCESSAMENTO_PENDENTE("PESQUISAR_SOLICITACAO_PROCESSAMENTO_PENDENTE", "OBTER_COUNT_SOLICITACAO_PROCESSAMENTO_PENDENTE"),
    PESQUISAR_SOLICITACAO_PROCESSAMENTO_FINALIZADO("PESQUISAR_SOLICITACAO_PROCESSAMENTO_FINALIZADO", "OBTER_COUNT_SOLICITACAO_PROCESSAMENTO_FINALIZADO"),
    PESQUISAR_HISTORICO_TARIFACAO_INSTRUCAO_BOLETO("PESQUISAR_CONSULTA_LANCAMENTO_TARIFA", "OBTER_CONSULTA_LANCAMENTO_TARIFA"),
    PESQUISAR_MOVIMENTO_CONTA_CORRENTE("PESQUISAR_MOVIMENTO_CONTA_CORRENTE", "OBTER_MOVIMENTO_CONTA_CORRENTE"),
    PESQUISAR_PARAMETRO("PESQUISAR_PARAMETRO", "OBTER_PARAMETRO"),
    PESQUISAR_PARAMETRO_INSTITUICAO("PESQUISAR_PARAMETRO_INSTITUICAO", "OBTER_PARAMETRO_INSTITUICAO"),
    PESQUISAR_SOLICITACAO_PROCESSAMENTO_INSTRUCAO_BOLETO("PESQUISAR_SOLICITACAO_PROCESSAMENTO_INSTRUCAO_BOLETO", "OBTER_SOLICITACAO_PROCESSAMENTO_INSTRUCAO_BOLETO"),
    PESQUISAR_SOLICITACAO_GERACAO_ARQUIVO_RETORNO("PESQUISAR_SOLICITACAO_GERACAO_ARQUIVO_RETORNO", "OBTER_PESQUISAR_SOLICITACAO_GERACAO_ARQUIVO_RETORNO"),
    PESQUISAR_PAINEL_MENSAGENSDDA("LISTAR_MENSAGENS_DDA", "OBTER_COUNT_MENSAGENSDDA"),
    PESQUISAR_PAINEL_LOGERROCARGA("LISTAR_LOG_ERRO_CARGA", "OBTER_COUNT_LOG_ERRO_CARGA"),
    PESQUISAR_PAINEL_NEGATIVACAO_EXCLUSAO("PESQUISAR_NEGATIVACAO_BOLETO_EXCLUSAO", "OBTER_PESQUISAR_NEGATIVACAO_BOLETO_EXCLUSAO"),
    PESQUISAR_RELATORIO_CONCILIACAO_NEGATIVACAO("PESQUISAR_RELATORIO_CONCILIACAO_NEGATIVACAO", "OBTER_PESQUISAR_RELATORIO_CONCILIACAO_NEGATIVACAO"),
    PESQUISAR_RELATORIO_CONTRATO_BENEFICIARIO("PESQUISAR_RELATORIO_CONTRATO_BENEFICIARIO", "OBTER_PESQUISAR_RELATORIO_CONTRATO_BENEFICIARIO"),
    PESQUISAR_TIPO_ERRO_CIP("PESQUISAR_TIPO_ERRO_CIP_PAGINADO", "OBTER_NUMERO_REGISTROS_TIPO_ERRO_CIP_PAGINADO"),
    PESQUISAR_TIPO_MENSAGEM("PESQUISAR_TIPO_MENSAGEM", "OBTER_QTD_TIPO_MENSAGEM"),
    PESQUISAR_ARQUIVO_RECEBIDO("PESQUISAR_ARQUIVO_RECEBIDO", "OBTER_QTD_ARQUIVO_RECEBIDO"),
    PESQUISAR_BENEFICIARIOS_ALERTA("PESQUISAR_BENEFICIARIOS_ALERTA", "OBTER_QTD_BENEFICIARIOS_ALERTA"),
    LISTAR_LOG_DET_RECEBIMENTO_ARQUIVODDA("LISTAR_LOG_DET_RECEBIMENTO_ARQUIVODDA", "OBTER_COUNT_LISTA_LOG_DET_RECEBIMENTO_ARQUIVODDA"),
    PESQUISAR_ARQUIVO_ENVIADO("PESQUISAR_ARQUIVO_ENVIADO", "OBTER_QTD_ARQUIVO_ENVIADO"),
    PESQUISAR_MENSAGEM_ERRO_CONTINGENCIA("PESQUISAR_MENSAGEM_ERRO_CONTINGENCIA", "OBTER_QTD_MENSAGEM_ERRO_CONTINGENCIA"),
    PESQUISAR_MENSAGEMDDABOLETODTO_TELA_PESQUISA("PESQUISAR_MENSAGEMDDABOLETODTO_TELA_PESQUISA", "OBTER_QTD_MENSAGEMDDABOLETODTO_TELA_PESQUISA"),
    PESQUISAR_BOLETO_PAGINADO("PESQUISAR_BOLETO_PAGINADO", "OBTER_NUMERO_REGISTROS_PESQUISAR_BOLETO_PAGINADO"),
    PESQUISAR_HISTORICO_MENSAGEM_106_PAGINADO("PESQUISAR_HISTORICO_MENSAGEM_106_PAGINADO", "OBTER_NUMERO_REGISTROS_PESQUISAR_HISTORICO_MENSAGEM_106_PAGINADO"),
    PESQUISAR_PAGADOR_ELETRONICO("PESQUISAR_PAGADOR_ELETRONICO", "OBTER_QTD_PESQUISAR_PAGADOR_ELETRONICO"),
    PESQUISAR_AGREGADO("PESQUISAR_AGREGADO", "OBTER_QTD_PESQUISAR_AGREGADO"),
    PESQUISAR_VISUALIZAR_RATEIO_TARIFAS("PESQUISA_RATEIO_PAGINADA", "OBTER_COUNT_RATEIO_PAGINADA");

    private final String nomePesquisa;
    private final String nomePesquisaNumRegistro;

    private PesquisaEnum(String nomePesquisa, String nomePesquisaNumRegistro) {
        this.nomePesquisa = nomePesquisa;
        this.nomePesquisaNumRegistro = nomePesquisaNumRegistro;
    }

    /**
     * @return the nomePesquisa
     */
    public String getNomePesquisa() {
        return nomePesquisa;
    }

    /**
     * @return the nomePesquisaNumRegistro
     */
    public String getNomePesquisaNumRegistro() {
        return nomePesquisaNumRegistro;
    }
}
