//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.26 at 05:37:01 PM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.arquivos.ADDA106;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for Grupo_ADDA106_BaixaOperacComplexType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grupo_ADDA106_BaixaOperacComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumIdentcBaixaOperac" type="{http://www.bcb.gov.br/ARQ/ADDA106.xsd}NumIdentcTit" minOccurs="0"/>
 *         &lt;element name="NumRefAtlBaixaOperac" type="{http://www.bcb.gov.br/ARQ/ADDA106.xsd}NumRefCad" minOccurs="0"/>
 *         &lt;element name="NumSeqAtlzBaixaOperac" type="{http://www.bcb.gov.br/ARQ/ADDA106.xsd}NumSeqAtlzCadDDA"/>
 *         &lt;element name="NumRefCadTitBaixaOperac" type="{http://www.bcb.gov.br/ARQ/ADDA106.xsd}NumRefCad" minOccurs="0"/>
 *         &lt;element name="NumRefAtlCadTitBaixaOperac" type="{http://www.bcb.gov.br/ARQ/ADDA106.xsd}NumRefCad" minOccurs="0"/>
 *         &lt;element name="ISPBPartRecbdrBaixaOperac" type="{http://www.bcb.gov.br/ARQ/ADDA106.xsd}ISPB"/>
 *         &lt;element name="CodPartRecbdrBaixaOperac" type="{http://www.bcb.gov.br/ARQ/ADDA106.xsd}CodIF" minOccurs="0"/>
 *         &lt;element name="TpBaixaOperac" type="{http://www.bcb.gov.br/ARQ/ADDA106.xsd}TpBaixaOperac"/>
 *         &lt;element name="SitBaixaOperac" type="{http://www.bcb.gov.br/ARQ/ADDA106.xsd}SitBaixaOperac"/>
 *         &lt;element name="DtHrSitBaixaOperac" type="{http://www.bcb.gov.br/ARQ/ADDA106.xsd}DataHora"/>
 *         &lt;element name="Grupo_ADDA106_DettBaixaOperac" type="{http://www.bcb.gov.br/ARQ/ADDA106.xsd}Grupo_ADDA106_DettBaixaOperacComplexType" minOccurs="0"/>
 *         &lt;element name="Grupo_ADDA106_CanceltBaixaOperac" type="{http://www.bcb.gov.br/ARQ/ADDA106.xsd}Grupo_ADDA106_CanceltBaixaOperacComplexType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grupo_ADDA106_BaixaOperacComplexType", propOrder = { "numIdentcBaixaOperac", "numRefAtlBaixaOperac", "numSeqAtlzBaixaOperac", "numRefCadTitBaixaOperac",
        "numRefAtlCadTitBaixaOperac", "ispbPartRecbdrBaixaOperac", "codPartRecbdrBaixaOperac", "tpBaixaOperac", "sitBaixaOperac", "dtHrSitBaixaOperac",
        "grupoADDA106DettBaixaOperac", "grupoADDA106CanceltBaixaOperac" })
public class GrupoADDA106BaixaOperacComplexType {

    @XmlElement(name = "NumIdentcBaixaOperac")
    private BigInteger numIdentcBaixaOperac;
    @XmlElement(name = "NumRefAtlBaixaOperac")
    private BigInteger numRefAtlBaixaOperac;
    @XmlElement(name = "NumSeqAtlzBaixaOperac", required = true)
    private BigInteger numSeqAtlzBaixaOperac;
    @XmlElement(name = "NumRefCadTitBaixaOperac")
    private BigInteger numRefCadTitBaixaOperac;
    @XmlElement(name = "NumRefAtlCadTitBaixaOperac")
    private BigInteger numRefAtlCadTitBaixaOperac;
    @XmlElement(name = "ISPBPartRecbdrBaixaOperac", required = true)
    private String ispbPartRecbdrBaixaOperac;
    @XmlElement(name = "CodPartRecbdrBaixaOperac")
    private String codPartRecbdrBaixaOperac;
    @XmlElement(name = "TpBaixaOperac", required = true)
    private String tpBaixaOperac;
    @XmlElement(name = "SitBaixaOperac", required = true)
    private String sitBaixaOperac;
    @XmlElement(name = "DtHrSitBaixaOperac", required = true)
    private XMLGregorianCalendar dtHrSitBaixaOperac;
    @XmlElement(name = "Grupo_ADDA106_DettBaixaOperac")
    private GrupoADDA106DettBaixaOperacComplexType grupoADDA106DettBaixaOperac;
    @XmlElement(name = "Grupo_ADDA106_CanceltBaixaOperac")
    private GrupoADDA106CanceltBaixaOperacComplexType grupoADDA106CanceltBaixaOperac;

    /**
     * Gets the value of the numIdentcBaixaOperac property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNumIdentcBaixaOperac() {
        return numIdentcBaixaOperac;
    }

    /**
     * Sets the value of the numIdentcBaixaOperac property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setNumIdentcBaixaOperac(BigInteger value) {
        this.numIdentcBaixaOperac = value;
    }

    /**
     * Gets the value of the numRefAtlBaixaOperac property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNumRefAtlBaixaOperac() {
        return numRefAtlBaixaOperac;
    }

    /**
     * Sets the value of the numRefAtlBaixaOperac property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setNumRefAtlBaixaOperac(BigInteger value) {
        this.numRefAtlBaixaOperac = value;
    }

    /**
     * Gets the value of the numSeqAtlzBaixaOperac property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNumSeqAtlzBaixaOperac() {
        return numSeqAtlzBaixaOperac;
    }

    /**
     * Sets the value of the numSeqAtlzBaixaOperac property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setNumSeqAtlzBaixaOperac(BigInteger value) {
        this.numSeqAtlzBaixaOperac = value;
    }

    /**
     * Gets the value of the numRefCadTitBaixaOperac property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNumRefCadTitBaixaOperac() {
        return numRefCadTitBaixaOperac;
    }

    /**
     * Sets the value of the numRefCadTitBaixaOperac property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setNumRefCadTitBaixaOperac(BigInteger value) {
        this.numRefCadTitBaixaOperac = value;
    }

    /**
     * Gets the value of the numRefAtlCadTitBaixaOperac property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNumRefAtlCadTitBaixaOperac() {
        return numRefAtlCadTitBaixaOperac;
    }

    /**
     * Sets the value of the numRefAtlCadTitBaixaOperac property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setNumRefAtlCadTitBaixaOperac(BigInteger value) {
        this.numRefAtlCadTitBaixaOperac = value;
    }

    /**
     * Gets the value of the ispbPartRecbdrBaixaOperac property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getISPBPartRecbdrBaixaOperac() {
        return ispbPartRecbdrBaixaOperac;
    }

    /**
     * Sets the value of the ispbPartRecbdrBaixaOperac property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setISPBPartRecbdrBaixaOperac(String value) {
        this.ispbPartRecbdrBaixaOperac = value;
    }

    /**
     * Gets the value of the codPartRecbdrBaixaOperac property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCodPartRecbdrBaixaOperac() {
        return codPartRecbdrBaixaOperac;
    }

    /**
     * Sets the value of the codPartRecbdrBaixaOperac property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCodPartRecbdrBaixaOperac(String value) {
        this.codPartRecbdrBaixaOperac = value;
    }

    /**
     * Gets the value of the tpBaixaOperac property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTpBaixaOperac() {
        return tpBaixaOperac;
    }

    /**
     * Sets the value of the tpBaixaOperac property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTpBaixaOperac(String value) {
        this.tpBaixaOperac = value;
    }

    /**
     * Gets the value of the sitBaixaOperac property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSitBaixaOperac() {
        return sitBaixaOperac;
    }

    /**
     * Sets the value of the sitBaixaOperac property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSitBaixaOperac(String value) {
        this.sitBaixaOperac = value;
    }

    /**
     * Gets the value of the dtHrSitBaixaOperac property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtHrSitBaixaOperac() {
        return dtHrSitBaixaOperac;
    }

    /**
     * Sets the value of the dtHrSitBaixaOperac property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtHrSitBaixaOperac(XMLGregorianCalendar value) {
        this.dtHrSitBaixaOperac = value;
    }

    /**
     * Gets the value of the grupoADDA106DettBaixaOperac property.
     * 
     * @return possible object is {@link GrupoADDA106DettBaixaOperacComplexType }
     * 
     */
    public GrupoADDA106DettBaixaOperacComplexType getGrupoADDA106DettBaixaOperac() {
        return grupoADDA106DettBaixaOperac;
    }

    /**
     * Sets the value of the grupoADDA106DettBaixaOperac property.
     * 
     * @param value allowed object is {@link GrupoADDA106DettBaixaOperacComplexType }
     * 
     */
    public void setGrupoADDA106DettBaixaOperac(GrupoADDA106DettBaixaOperacComplexType value) {
        this.grupoADDA106DettBaixaOperac = value;
    }

    /**
     * Gets the value of the grupoADDA106CanceltBaixaOperac property.
     * 
     * @return possible object is {@link GrupoADDA106CanceltBaixaOperacComplexType }
     * 
     */
    public GrupoADDA106CanceltBaixaOperacComplexType getGrupoADDA106CanceltBaixaOperac() {
        return grupoADDA106CanceltBaixaOperac;
    }

    /**
     * Sets the value of the grupoADDA106CanceltBaixaOperac property.
     * 
     * @param value allowed object is {@link GrupoADDA106CanceltBaixaOperacComplexType }
     * 
     */
    public void setGrupoADDA106CanceltBaixaOperac(GrupoADDA106CanceltBaixaOperacComplexType value) {
        this.grupoADDA106CanceltBaixaOperac = value;
    }

}
