//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.26 at 05:37:01 PM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.arquivos.ADDA106;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.arquivos.ADDA106 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can
 * consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods
 * for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.arquivos.ADDA106
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GrupoADDA106TercComplexType }
     * 
     */
    public GrupoADDA106TercComplexType createGrupoADDA106TercComplexType() {
        return new GrupoADDA106TercComplexType();
    }

    /**
     * Create an instance of {@link GrupoADDA106TitComplexType }
     * 
     */
    public GrupoADDA106TitComplexType createGrupoADDA106TitComplexType() {
        return new GrupoADDA106TitComplexType();
    }

    /**
     * Create an instance of {@link GrupoADDA106MultaTitComplexType }
     * 
     */
    public GrupoADDA106MultaTitComplexType createGrupoADDA106MultaTitComplexType() {
        return new GrupoADDA106MultaTitComplexType();
    }

    /**
     * Create an instance of {@link GrupoADDA106DesctTitComplexType }
     * 
     */
    public GrupoADDA106DesctTitComplexType createGrupoADDA106DesctTitComplexType() {
        return new GrupoADDA106DesctTitComplexType();
    }

    /**
     * Create an instance of {@link GrupoADDA106JurosTitComplexType }
     * 
     */
    public GrupoADDA106JurosTitComplexType createGrupoADDA106JurosTitComplexType() {
        return new GrupoADDA106JurosTitComplexType();
    }

    /**
     * Create an instance of {@link GrupoADDA106BaixaOperacComplexType }
     * 
     */
    public GrupoADDA106BaixaOperacComplexType createGrupoADDA106BaixaOperacComplexType() {
        return new GrupoADDA106BaixaOperacComplexType();
    }

    /**
     * Create an instance of {@link GrupoADDA106NotaFisComplexType }
     * 
     */
    public GrupoADDA106NotaFisComplexType createGrupoADDA106NotaFisComplexType() {
        return new GrupoADDA106NotaFisComplexType();
    }

    /**
     * Create an instance of {@link GrupoADDA106CalcComplexType }
     * 
     */
    public GrupoADDA106CalcComplexType createGrupoADDA106CalcComplexType() {
        return new GrupoADDA106CalcComplexType();
    }

    /**
     * Create an instance of {@link GrupoADDA106CanceltBaixaOperacComplexType }
     * 
     */
    public GrupoADDA106CanceltBaixaOperacComplexType createGrupoADDA106CanceltBaixaOperacComplexType() {
        return new GrupoADDA106CanceltBaixaOperacComplexType();
    }

    /**
     * Create an instance of {@link SISARQComplexType }
     * 
     */
    public SISARQComplexType createSISARQComplexType() {
        return new SISARQComplexType();
    }

    /**
     * Create an instance of {@link GrupoADDA106BaixaEftComplexType }
     * 
     */
    public GrupoADDA106BaixaEftComplexType createGrupoADDA106BaixaEftComplexType() {
        return new GrupoADDA106BaixaEftComplexType();
    }

    /**
     * Create an instance of {@link GrupoADDA106DettBaixaOperacComplexType }
     * 
     */
    public GrupoADDA106DettBaixaOperacComplexType createGrupoADDA106DettBaixaOperacComplexType() {
        return new GrupoADDA106DettBaixaOperacComplexType();
    }

    /**
     * Create an instance of {@link ADDA106ComplexType }
     * 
     */
    public ADDA106ComplexType createADDA106ComplexType() {
        return new ADDA106ComplexType();
    }

}
