//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.09 at 10:55:26 AM BRT 
//


package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0004;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DDA0004ComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DDA0004ComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodMsg" type="{http://www.bcb.gov.br/MES/DDA0004.xsd}CodMsg"/>
 *         &lt;element name="ISPBPartRecbdrPrincipal" type="{http://www.bcb.gov.br/MES/DDA0004.xsd}ISPB"/>
 *         &lt;element name="ISPBPartRecbdrAdmtd" type="{http://www.bcb.gov.br/MES/DDA0004.xsd}ISPB"/>
 *         &lt;element name="NumCtrlDDA" type="{http://www.bcb.gov.br/MES/DDA0004.xsd}ControleIF"/>
 *         &lt;element name="IndrManutPagdr" type="{http://www.bcb.gov.br/MES/DDA0004.xsd}IndrIEA"/>
 *         &lt;element name="NumIdentcPagdr" type="{http://www.bcb.gov.br/MES/DDA0004.xsd}NumIdentcPagdr"/>
 *         &lt;element name="NumRefAtlCadPagdr" type="{http://www.bcb.gov.br/MES/DDA0004.xsd}NumRefCad"/>
 *         &lt;element name="NumSeqAtlzCadPagdr" type="{http://www.bcb.gov.br/MES/DDA0004.xsd}NumSeqAtlzCadDDA"/>
 *         &lt;element name="QtdAdesPagdrDDA" type="{http://www.bcb.gov.br/MES/DDA0004.xsd}QtdAdesPagdrDDA"/>
 *         &lt;element name="DtHrSitAdesPagdrDDA" type="{http://www.bcb.gov.br/MES/DDA0004.xsd}DataHora"/>
 *         &lt;element name="DtHrDDA" type="{http://www.bcb.gov.br/MES/DDA0004.xsd}DataHora"/>
 *         &lt;element name="DtMovto" type="{http://www.bcb.gov.br/MES/DDA0004.xsd}Data"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DDA0004ComplexType", propOrder = {
    "codMsg",
    "ispbPartRecbdrPrincipal",
    "ispbPartRecbdrAdmtd",
    "numCtrlDDA",
    "indrManutPagdr",
    "numIdentcPagdr",
    "numRefAtlCadPagdr",
    "numSeqAtlzCadPagdr",
    "qtdAdesPagdrDDA",
    "dtHrSitAdesPagdrDDA",
    "dtHrDDA",
    "dtMovto"
})
public class DDA0004ComplexType {

    @XmlElement(name = "CodMsg", required = true)
    private String codMsg;
    @XmlElement(name = "ISPBPartRecbdrPrincipal", required = true)
    private String ispbPartRecbdrPrincipal;
    @XmlElement(name = "ISPBPartRecbdrAdmtd", required = true)
    private String ispbPartRecbdrAdmtd;
    @XmlElement(name = "NumCtrlDDA", required = true)
    private String numCtrlDDA;
    @XmlElement(name = "IndrManutPagdr", required = true)
    private String indrManutPagdr;
    @XmlElement(name = "NumIdentcPagdr", required = true)
    private BigInteger numIdentcPagdr;
    @XmlElement(name = "NumRefAtlCadPagdr", required = true)
    private BigInteger numRefAtlCadPagdr;
    @XmlElement(name = "NumSeqAtlzCadPagdr", required = true)
    private BigInteger numSeqAtlzCadPagdr;
    @XmlElement(name = "QtdAdesPagdrDDA", required = true)
    private BigInteger qtdAdesPagdrDDA;
    @XmlElement(name = "DtHrSitAdesPagdrDDA", required = true)
    private XMLGregorianCalendar dtHrSitAdesPagdrDDA;
    @XmlElement(name = "DtHrDDA", required = true)
    private XMLGregorianCalendar dtHrDDA;
    @XmlElement(name = "DtMovto", required = true)
    private XMLGregorianCalendar dtMovto;

    /**
     * Gets the value of the codMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodMsg() {
        return codMsg;
    }

    /**
     * Sets the value of the codMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodMsg(String value) {
        this.codMsg = value;
    }

    /**
     * Gets the value of the ispbPartRecbdrPrincipal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISPBPartRecbdrPrincipal() {
        return ispbPartRecbdrPrincipal;
    }

    /**
     * Sets the value of the ispbPartRecbdrPrincipal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISPBPartRecbdrPrincipal(String value) {
        this.ispbPartRecbdrPrincipal = value;
    }

    /**
     * Gets the value of the ispbPartRecbdrAdmtd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISPBPartRecbdrAdmtd() {
        return ispbPartRecbdrAdmtd;
    }

    /**
     * Sets the value of the ispbPartRecbdrAdmtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISPBPartRecbdrAdmtd(String value) {
        this.ispbPartRecbdrAdmtd = value;
    }

    /**
     * Gets the value of the numCtrlDDA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumCtrlDDA() {
        return numCtrlDDA;
    }

    /**
     * Sets the value of the numCtrlDDA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumCtrlDDA(String value) {
        this.numCtrlDDA = value;
    }

    /**
     * Gets the value of the indrManutPagdr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndrManutPagdr() {
        return indrManutPagdr;
    }

    /**
     * Sets the value of the indrManutPagdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndrManutPagdr(String value) {
        this.indrManutPagdr = value;
    }

    /**
     * Gets the value of the numIdentcPagdr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumIdentcPagdr() {
        return numIdentcPagdr;
    }

    /**
     * Sets the value of the numIdentcPagdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumIdentcPagdr(BigInteger value) {
        this.numIdentcPagdr = value;
    }

    /**
     * Gets the value of the numRefAtlCadPagdr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumRefAtlCadPagdr() {
        return numRefAtlCadPagdr;
    }

    /**
     * Sets the value of the numRefAtlCadPagdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumRefAtlCadPagdr(BigInteger value) {
        this.numRefAtlCadPagdr = value;
    }

    /**
     * Gets the value of the numSeqAtlzCadPagdr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumSeqAtlzCadPagdr() {
        return numSeqAtlzCadPagdr;
    }

    /**
     * Sets the value of the numSeqAtlzCadPagdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumSeqAtlzCadPagdr(BigInteger value) {
        this.numSeqAtlzCadPagdr = value;
    }

    /**
     * Gets the value of the qtdAdesPagdrDDA property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQtdAdesPagdrDDA() {
        return qtdAdesPagdrDDA;
    }

    /**
     * Sets the value of the qtdAdesPagdrDDA property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQtdAdesPagdrDDA(BigInteger value) {
        this.qtdAdesPagdrDDA = value;
    }

    /**
     * Gets the value of the dtHrSitAdesPagdrDDA property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtHrSitAdesPagdrDDA() {
        return dtHrSitAdesPagdrDDA;
    }

    /**
     * Sets the value of the dtHrSitAdesPagdrDDA property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtHrSitAdesPagdrDDA(XMLGregorianCalendar value) {
        this.dtHrSitAdesPagdrDDA = value;
    }

    /**
     * Gets the value of the dtHrDDA property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtHrDDA() {
        return dtHrDDA;
    }

    /**
     * Sets the value of the dtHrDDA property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtHrDDA(XMLGregorianCalendar value) {
        this.dtHrDDA = value;
    }

    /**
     * Gets the value of the dtMovto property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtMovto() {
        return dtMovto;
    }

    /**
     * Sets the value of the dtMovto property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtMovto(XMLGregorianCalendar value) {
        this.dtMovto = value;
    }

}
