//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.09 at 10:55:26 AM BRT 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0004;

import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0004 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can
 * consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods
 * for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DOC_QNAME = new QName("http://www.bcb.gov.br/MES/DDA0004.xsd", "DOC");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0004
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GrupoSeqComplexType }
     * 
     */
    public GrupoSeqComplexType createGrupoSeqComplexType() {
        return new GrupoSeqComplexType();
    }

    /**
     * Create an instance of {@link DDA0004ComplexType }
     * 
     */
    public DDA0004ComplexType createDDA0004ComplexType() {
        return new DDA0004ComplexType();
    }
}
