//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.26 at 05:37:06 PM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.arquivos.ADDA118;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.arquivos.ADDA118 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can
 * consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods
 * for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.arquivos.ADDA118
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GrupoADDA118RR2TitComplexType }
     * 
     */
    public GrupoADDA118RR2TitComplexType createGrupoADDA118RR2TitComplexType() {
        return new GrupoADDA118RR2TitComplexType();
    }

    /**
     * Create an instance of {@link GrupoADDA118TitComplexType }
     * 
     */
    public GrupoADDA118TitComplexType createGrupoADDA118TitComplexType() {
        return new GrupoADDA118TitComplexType();
    }

    /**
     * Create an instance of {@link ADDA118RR2ComplexType }
     * 
     */
    public ADDA118RR2ComplexType createADDA118RR2ComplexType() {
        return new ADDA118RR2ComplexType();
    }

    /**
     * Create an instance of {@link GrupoADDA118RETTitActoComplexType }
     * 
     */
    public GrupoADDA118RETTitActoComplexType createGrupoADDA118RETTitActoComplexType() {
        return new GrupoADDA118RETTitActoComplexType();
    }

    /**
     * Create an instance of {@link SISARQComplexType }
     * 
     */
    public SISARQComplexType createSISARQComplexType() {
        return new SISARQComplexType();
    }

    /**
     * Create an instance of {@link ADDA118ComplexType }
     * 
     */
    public ADDA118ComplexType createADDA118ComplexType() {
        return new ADDA118ComplexType();
    }

}
