//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 09:22:39 AM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0214;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0214 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can
 * consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods
 * for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0214
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DDA0214ComplexType }
     * 
     */
    public DDA0214ComplexType createDDA0214ComplexType() {
        return new DDA0214ComplexType();
    }

    /**
     * Create an instance of {@link GrupoDDA0214R1ArqComplexType }
     * 
     */
    public GrupoDDA0214R1ArqComplexType createGrupoDDA0214R1ArqComplexType() {
        return new GrupoDDA0214R1ArqComplexType();
    }

    /**
     * Create an instance of {@link DDA0214R1ComplexType }
     * 
     */
    public DDA0214R1ComplexType createDDA0214R1ComplexType() {
        return new DDA0214R1ComplexType();
    }

    /**
     * Create an instance of {@link GrupoDDA0214R1MsgComplexType }
     * 
     */
    public GrupoDDA0214R1MsgComplexType createGrupoDDA0214R1MsgComplexType() {
        return new GrupoDDA0214R1MsgComplexType();
    }

}
