//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 09:22:30 AM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0110;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0110 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can
 * consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods
 * for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0110
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GrupoDDA0110R1JurosTitComplexType }
     * 
     */
    public GrupoDDA0110R1JurosTitComplexType createGrupoDDA0110R1JurosTitComplexType() {
        return new GrupoDDA0110R1JurosTitComplexType();
    }

    /**
     * Create an instance of {@link DDA0110ComplexType }
     * 
     */
    public DDA0110ComplexType createDDA0110ComplexType() {
        return new DDA0110ComplexType();
    }

    /**
     * Create an instance of {@link GrupoDDA0110R1BaixaEftComplexType }
     * 
     */
    public GrupoDDA0110R1BaixaEftComplexType createGrupoDDA0110R1BaixaEftComplexType() {
        return new GrupoDDA0110R1BaixaEftComplexType();
    }

    /**
     * Create an instance of {@link GrupoDDA0110R1DesctTitComplexType }
     * 
     */
    public GrupoDDA0110R1DesctTitComplexType createGrupoDDA0110R1DesctTitComplexType() {
        return new GrupoDDA0110R1DesctTitComplexType();
    }

    /**
     * Create an instance of {@link GrupoDDA0110R1BaixaOperacComplexType }
     * 
     */
    public GrupoDDA0110R1BaixaOperacComplexType createGrupoDDA0110R1BaixaOperacComplexType() {
        return new GrupoDDA0110R1BaixaOperacComplexType();
    }

    /**
     * Create an instance of {@link DDA0110R1ComplexType }
     * 
     */
    public DDA0110R1ComplexType createDDA0110R1ComplexType() {
        return new DDA0110R1ComplexType();
    }

    /**
     * Create an instance of {@link GrupoDDA0110R1MultaTitComplexType }
     * 
     */
    public GrupoDDA0110R1MultaTitComplexType createGrupoDDA0110R1MultaTitComplexType() {
        return new GrupoDDA0110R1MultaTitComplexType();
    }

    /**
     * Create an instance of {@link GrupoDDA0110R1CalcComplexType }
     * 
     */
    public GrupoDDA0110R1CalcComplexType createGrupoDDA0110R1CalcComplexType() {
        return new GrupoDDA0110R1CalcComplexType();
    }

}
