//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 09:58:01 AM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0215;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.ComplexType;

/**
 * <p>
 * Java class for DDA0215ComplexType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DDA0215ComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodMsg" type="{http://www.bcb.gov.br/SPB/DDA0215.xsd}CodMsg"/>
 *         &lt;element name="NumCtrlPart" type="{http://www.bcb.gov.br/SPB/DDA0215.xsd}ControleIF"/>
 *         &lt;element name="ISPBPartPrincipal" type="{http://www.bcb.gov.br/SPB/DDA0215.xsd}ISPB"/>
 *         &lt;element name="TpMsg_Arq" type="{http://www.bcb.gov.br/SPB/DDA0215.xsd}TpMsg_Arq"/>
 *         &lt;element name="CodMsg_Arq" type="{http://www.bcb.gov.br/SPB/DDA0215.xsd}CodMsg_Arq"/>
 *         &lt;element name="Grupo_DDA0215_Dett" type="{http://www.bcb.gov.br/SPB/DDA0215.xsd}Grupo_DDA0215_DettComplexType" maxOccurs="unbounded"/>
 *         &lt;element name="DtMovto" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DDA0215ComplexType", propOrder = { "codMsg", "numCtrlPart", "ispbPartPrincipal", "tpMsgArq", "codMsgArq", "grupoDDA0215Dett", "dtMovto" })
public class DDA0215ComplexType implements ComplexType {

    @XmlElement(name = "CodMsg", required = true)
    private String codMsg;
    @XmlElement(name = "NumCtrlPart", required = true)
    private String numCtrlPart;
    @XmlElement(name = "ISPBPartPrincipal", required = true)
    private String ispbPartPrincipal;
    @XmlElement(name = "TpMsg_Arq", required = true)
    private String tpMsgArq;
    @XmlElement(name = "CodMsg_Arq", required = true)
    private String codMsgArq;
    @XmlElement(name = "Grupo_DDA0215_Dett", required = true)
    private List<GrupoDDA0215DettComplexType> grupoDDA0215Dett;
    @XmlElement(name = "DtMovto", required = true)
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar dtMovto;

    /**
     * Gets the value of the codMsg property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCodMsg() {
        return codMsg;
    }

    /**
     * Sets the value of the codMsg property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCodMsg(String value) {
        this.codMsg = value;
    }

    /**
     * Gets the value of the numCtrlPart property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNumCtrlPart() {
        return numCtrlPart;
    }

    /**
     * Sets the value of the numCtrlPart property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNumCtrlPart(String value) {
        this.numCtrlPart = value;
    }

    /**
     * Gets the value of the ispbPartPrincipal property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getISPBPartPrincipal() {
        return ispbPartPrincipal;
    }

    /**
     * Sets the value of the ispbPartPrincipal property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setISPBPartPrincipal(String value) {
        this.ispbPartPrincipal = value;
    }

    /**
     * Gets the value of the tpMsgArq property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTpMsgArq() {
        return tpMsgArq;
    }

    /**
     * Sets the value of the tpMsgArq property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTpMsgArq(String value) {
        this.tpMsgArq = value;
    }

    /**
     * Gets the value of the codMsgArq property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCodMsgArq() {
        return codMsgArq;
    }

    /**
     * Sets the value of the codMsgArq property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCodMsgArq(String value) {
        this.codMsgArq = value;
    }

    /**
     * Gets the value of the grupoDDA0215Dett property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the grupoDDA0215Dett property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getGrupoDDA0215Dett().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link GrupoDDA0215DettComplexType }
     * 
     * 
     */
    public List<GrupoDDA0215DettComplexType> getGrupoDDA0215Dett() {
        if (grupoDDA0215Dett == null) {
            grupoDDA0215Dett = new ArrayList<GrupoDDA0215DettComplexType>();
        }
        return this.grupoDDA0215Dett;
    }

    /**
     * Gets the value of the dtMovto property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtMovto() {
        return dtMovto;
    }

    /**
     * Sets the value of the dtMovto property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtMovto(XMLGregorianCalendar value) {
        this.dtMovto = value;
    }

    /**
     * {@inheritDoc}
     * 
     * @see br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.ComplexType#setIdMensagemDDA(java.lang.String)
     */
    public void setIdMensagemDDA(String id) {
        setNumCtrlPart(id);
    }

}
