//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 09:58:01 AM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0215;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Grupo_DDA0215R1_DettComplexType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grupo_DDA0215R1_DettComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NUOpOr" type="{http://www.bcb.gov.br/SPB/DDA0215.xsd}NUOp" minOccurs="0"/>
 *         &lt;element name="NUOpMsg" type="{http://www.bcb.gov.br/SPB/DDA0215.xsd}NUOp" minOccurs="0"/>
 *         &lt;element name="IdentdArqOr" type="{http://www.bcb.gov.br/SPB/DDA0215.xsd}IdentdArq" minOccurs="0"/>
 *         &lt;element name="IdentdArq" type="{http://www.bcb.gov.br/SPB/DDA0215.xsd}IdentdArq" minOccurs="0"/>
 *         &lt;element name="SitReqDDADett" type="{http://www.bcb.gov.br/SPB/DDA0215.xsd}SitCons"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grupo_DDA0215R1_DettComplexType", propOrder = { "nuOpOr", "nuOpMsg", "identdArqOr", "identdArq", "sitReqDDADett" })
public class GrupoDDA0215R1DettComplexType {

    @XmlElement(name = "NUOpOr")
    private String nuOpOr;
    @XmlElement(name = "NUOpMsg")
    private String nuOpMsg;
    @XmlElement(name = "IdentdArqOr")
    private String identdArqOr;
    @XmlElement(name = "IdentdArq")
    private String identdArq;
    @XmlElement(name = "SitReqDDADett", required = true)
    private BigInteger sitReqDDADett;

    /**
     * Gets the value of the nuOpOr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNUOpOr() {
        return nuOpOr;
    }

    /**
     * Sets the value of the nuOpOr property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNUOpOr(String value) {
        this.nuOpOr = value;
    }

    /**
     * Gets the value of the nuOpMsg property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNUOpMsg() {
        return nuOpMsg;
    }

    /**
     * Sets the value of the nuOpMsg property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNUOpMsg(String value) {
        this.nuOpMsg = value;
    }

    /**
     * Gets the value of the identdArqOr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIdentdArqOr() {
        return identdArqOr;
    }

    /**
     * Sets the value of the identdArqOr property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIdentdArqOr(String value) {
        this.identdArqOr = value;
    }

    /**
     * Gets the value of the identdArq property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIdentdArq() {
        return identdArq;
    }

    /**
     * Sets the value of the identdArq property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIdentdArq(String value) {
        this.identdArq = value;
    }

    /**
     * Gets the value of the sitReqDDADett property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getSitReqDDADett() {
        return sitReqDDADett;
    }

    /**
     * Sets the value of the sitReqDDADett property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setSitReqDDADett(BigInteger value) {
        this.sitReqDDADett = value;
    }

}
