//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.23 at 04:27:45 PM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0502;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Grupo_DDA0502_ReprtteCliBenfcrioComplexType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grupo_DDA0502_ReprtteCliBenfcrioComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TpManutReprtteCliBenfcrio" type="{http://www.bcb.gov.br/SPB/DDA0502.xsd}IndrIE"/>
 *         &lt;element name="TpPessoaReprtteCliBenfcrio" type="{http://www.bcb.gov.br/SPB/DDA0502.xsd}TpPessoa"/>
 *         &lt;element name="CNPJ_CPFReprtteCliBenfcrio" type="{http://www.bcb.gov.br/SPB/DDA0502.xsd}CNPJ_CPF"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grupo_DDA0502_ReprtteCliBenfcrioComplexTypeNPC", propOrder = { "tpManutReprtteCliBenfcrio", "tpPessoaReprtteCliBenfcrio", "cnpjcpfReprtteCliBenfcrio" })
public class GrupoDDA0502ReprtteCliBenfcrioComplexType {

    @XmlElement(name = "TpManutReprtteCliBenfcrio", required = true)
    private String tpManutReprtteCliBenfcrio;
    @XmlElement(name = "TpPessoaReprtteCliBenfcrio", required = true)
    private String tpPessoaReprtteCliBenfcrio;
    @XmlElement(name = "CNPJ_CPFReprtteCliBenfcrio", required = true)
    private BigInteger cnpjcpfReprtteCliBenfcrio;

    /**
     * Gets the value of the tpManutReprtteCliBenfcrio property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTpManutReprtteCliBenfcrio() {
        return tpManutReprtteCliBenfcrio;
    }

    /**
     * Sets the value of the tpManutReprtteCliBenfcrio property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTpManutReprtteCliBenfcrio(String value) {
        this.tpManutReprtteCliBenfcrio = value;
    }

    /**
     * Gets the value of the tpPessoaReprtteCliBenfcrio property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTpPessoaReprtteCliBenfcrio() {
        return tpPessoaReprtteCliBenfcrio;
    }

    /**
     * Sets the value of the tpPessoaReprtteCliBenfcrio property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTpPessoaReprtteCliBenfcrio(String value) {
        this.tpPessoaReprtteCliBenfcrio = value;
    }

    /**
     * Gets the value of the cnpjcpfReprtteCliBenfcrio property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getCNPJCPFReprtteCliBenfcrio() {
        return cnpjcpfReprtteCliBenfcrio;
    }

    /**
     * Sets the value of the cnpjcpfReprtteCliBenfcrio property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setCNPJCPFReprtteCliBenfcrio(BigInteger value) {
        this.cnpjcpfReprtteCliBenfcrio = value;
    }

}
