//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.23 at 04:30:41 PM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0504;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Grupo_DDA0504_BenfcrioComplexType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grupo_DDA0504_BenfcrioComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TpPessoaBenfcrio" type="{http://www.bcb.gov.br/SPB/DDA0504.xsd}TpPessoa"/>
 *         &lt;element name="CNPJ_CPFBenfcrio" type="{http://www.bcb.gov.br/SPB/DDA0504.xsd}CNPJ_CPF"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grupo_DDA0504_BenfcrioComplexType", propOrder = { "tpPessoaBenfcrio", "cnpjcpfBenfcrio" })
public class GrupoDDA0504BenfcrioComplexType {

    @XmlElement(name = "TpPessoaBenfcrio", required = true)
    private String tpPessoaBenfcrio;
    @XmlElement(name = "CNPJ_CPFBenfcrio", required = true)
    private BigInteger cnpjcpfBenfcrio;

    /**
     * Gets the value of the tpPessoaBenfcrio property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTpPessoaBenfcrio() {
        return tpPessoaBenfcrio;
    }

    /**
     * Sets the value of the tpPessoaBenfcrio property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTpPessoaBenfcrio(String value) {
        this.tpPessoaBenfcrio = value;
    }

    /**
     * Gets the value of the cnpjcpfBenfcrio property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getCNPJCPFBenfcrio() {
        return cnpjcpfBenfcrio;
    }

    /**
     * Sets the value of the cnpjcpfBenfcrio property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setCNPJCPFBenfcrio(BigInteger value) {
        this.cnpjcpfBenfcrio = value;
    }

}
