//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 09:22:34 AM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0121;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for Grupo_DDA0121R3_CanceltBaixaOperacComplexType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grupo_DDA0121R3_CanceltBaixaOperacComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DtHrCanceltBaixaOperac" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DtCanceltBaixaOperac" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grupo_DDA0121R3_CanceltBaixaOperacComplexType", propOrder = { "dtHrCanceltBaixaOperac", "dtCanceltBaixaOperac" })
public class GrupoDDA0121R3CanceltBaixaOperacComplexType {

    @XmlElement(name = "DtHrCanceltBaixaOperac", required = true)
    @XmlSchemaType(name = "dateTime")
    private XMLGregorianCalendar dtHrCanceltBaixaOperac;
    @XmlElement(name = "DtCanceltBaixaOperac", required = true)
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar dtCanceltBaixaOperac;

    /**
     * Gets the value of the dtHrCanceltBaixaOperac property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtHrCanceltBaixaOperac() {
        return dtHrCanceltBaixaOperac;
    }

    /**
     * Sets the value of the dtHrCanceltBaixaOperac property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtHrCanceltBaixaOperac(XMLGregorianCalendar value) {
        this.dtHrCanceltBaixaOperac = value;
    }

    /**
     * Gets the value of the dtCanceltBaixaOperac property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtCanceltBaixaOperac() {
        return dtCanceltBaixaOperac;
    }

    /**
     * Sets the value of the dtCanceltBaixaOperac property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtCanceltBaixaOperac(XMLGregorianCalendar value) {
        this.dtCanceltBaixaOperac = value;
    }

}
