//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 09:22:19 AM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0002;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import br.com.sicoob.sisbr.sicoobdda.entidades.TipoMensagemDDA;
import br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.sspb.recebimento.ConteudoMsgRecebida;

/**
 * <p>
 * Java class for Grupo_DDA0002R1_PagdrComplexType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grupo_DDA0002R1_PagdrComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TpPessoaPagdr" type="{http://www.bcb.gov.br/SPB/DDA0002.xsd}TpPessoa"/>
 *         &lt;element name="CNPJ_CPFPagdr" type="{http://www.bcb.gov.br/SPB/DDA0002.xsd}CNPJ_CPF"/>
 *         &lt;element name="SitCliPagdrDDA" type="{http://www.bcb.gov.br/SPB/DDA0002.xsd}SitCliPagdrDDA"/>
 *         &lt;element name="DtHrSitAdesCliPagdrDDA" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="IndrAdesCliPagdrDDA" type="{http://www.bcb.gov.br/SPB/DDA0002.xsd}Indr"/>
 *         &lt;element name="QtdAdesCliPagdrDDA" type="{http://www.bcb.gov.br/SPB/DDA0002.xsd}Qtd" minOccurs="0"/>
 *         &lt;element name="DtHrIniCadCliPagdrDDA" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="DtHrFimCadCliPagdrDDA" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Grupo_DDA0002R1_PagdrProprio" type="{http://www.bcb.gov.br/SPB/DDA0002.xsd}Grupo_DDA0002R1_PagdrProprioComplexType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grupo_DDA0002R1_PagdrComplexType", propOrder = { "tpPessoaPagdr", "cnpjcpfPagdr", "sitCliPagdrDDA", "dtHrSitAdesCliPagdrDDA", "indrAdesCliPagdrDDA",
        "qtdAdesCliPagdrDDA", "dtHrIniCadCliPagdrDDA", "dtHrFimCadCliPagdrDDA", "grupoDDA0002R1PagdrProprio" })
public class GrupoDDA0002R1PagdrComplexType implements ConteudoMsgRecebida {

    @XmlElement(name = "TpPessoaPagdr", required = true)
    private String tpPessoaPagdr;
    @XmlElement(name = "CNPJ_CPFPagdr", required = true)
    private BigInteger cnpjcpfPagdr;
    @XmlElement(name = "SitCliPagdrDDA", required = true)
    private String sitCliPagdrDDA;
    @XmlElement(name = "DtHrSitAdesCliPagdrDDA")
    @XmlSchemaType(name = "dateTime")
    private XMLGregorianCalendar dtHrSitAdesCliPagdrDDA;
    @XmlElement(name = "IndrAdesCliPagdrDDA", required = true)
    private String indrAdesCliPagdrDDA;
    @XmlElement(name = "QtdAdesCliPagdrDDA")
    private BigInteger qtdAdesCliPagdrDDA;
    @XmlElement(name = "DtHrIniCadCliPagdrDDA")
    @XmlSchemaType(name = "dateTime")
    private XMLGregorianCalendar dtHrIniCadCliPagdrDDA;
    @XmlElement(name = "DtHrFimCadCliPagdrDDA")
    @XmlSchemaType(name = "dateTime")
    private XMLGregorianCalendar dtHrFimCadCliPagdrDDA;
    @XmlElement(name = "Grupo_DDA0002R1_PagdrProprio")
    private GrupoDDA0002R1PagdrProprioComplexType grupoDDA0002R1PagdrProprio;

    /**
     * Gets the value of the tpPessoaPagdr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTpPessoaPagdr() {
        return tpPessoaPagdr;
    }

    /**
     * Sets the value of the tpPessoaPagdr property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTpPessoaPagdr(String value) {
        this.tpPessoaPagdr = value;
    }

    /**
     * Gets the value of the cnpjcpfPagdr property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getCNPJCPFPagdr() {
        return cnpjcpfPagdr;
    }

    /**
     * Sets the value of the cnpjcpfPagdr property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setCNPJCPFPagdr(BigInteger value) {
        this.cnpjcpfPagdr = value;
    }

    /**
     * Gets the value of the sitCliPagdrDDA property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSitCliPagdrDDA() {
        return sitCliPagdrDDA;
    }

    /**
     * Sets the value of the sitCliPagdrDDA property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSitCliPagdrDDA(String value) {
        this.sitCliPagdrDDA = value;
    }

    /**
     * Gets the value of the dtHrSitAdesCliPagdrDDA property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtHrSitAdesCliPagdrDDA() {
        return dtHrSitAdesCliPagdrDDA;
    }

    /**
     * Sets the value of the dtHrSitAdesCliPagdrDDA property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtHrSitAdesCliPagdrDDA(XMLGregorianCalendar value) {
        this.dtHrSitAdesCliPagdrDDA = value;
    }

    /**
     * Gets the value of the indrAdesCliPagdrDDA property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIndrAdesCliPagdrDDA() {
        return indrAdesCliPagdrDDA;
    }

    /**
     * Sets the value of the indrAdesCliPagdrDDA property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIndrAdesCliPagdrDDA(String value) {
        this.indrAdesCliPagdrDDA = value;
    }

    /**
     * Gets the value of the qtdAdesCliPagdrDDA property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getQtdAdesCliPagdrDDA() {
        return qtdAdesCliPagdrDDA;
    }

    /**
     * Sets the value of the qtdAdesCliPagdrDDA property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setQtdAdesCliPagdrDDA(BigInteger value) {
        this.qtdAdesCliPagdrDDA = value;
    }

    /**
     * Gets the value of the dtHrIniCadCliPagdrDDA property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtHrIniCadCliPagdrDDA() {
        return dtHrIniCadCliPagdrDDA;
    }

    /**
     * Sets the value of the dtHrIniCadCliPagdrDDA property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtHrIniCadCliPagdrDDA(XMLGregorianCalendar value) {
        this.dtHrIniCadCliPagdrDDA = value;
    }

    /**
     * Gets the value of the dtHrFimCadCliPagdrDDA property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtHrFimCadCliPagdrDDA() {
        return dtHrFimCadCliPagdrDDA;
    }

    /**
     * Sets the value of the dtHrFimCadCliPagdrDDA property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtHrFimCadCliPagdrDDA(XMLGregorianCalendar value) {
        this.dtHrFimCadCliPagdrDDA = value;
    }

    /**
     * Gets the value of the grupoDDA0002R1PagdrProprio property.
     * 
     * @return possible object is {@link GrupoDDA0002R1PagdrProprioComplexType }
     * 
     */
    public GrupoDDA0002R1PagdrProprioComplexType getGrupoDDA0002R1PagdrProprio() {
        return grupoDDA0002R1PagdrProprio;
    }

    /**
     * Sets the value of the grupoDDA0002R1PagdrProprio property.
     * 
     * @param value allowed object is {@link GrupoDDA0002R1PagdrProprioComplexType }
     * 
     */
    public void setGrupoDDA0002R1PagdrProprio(GrupoDDA0002R1PagdrProprioComplexType value) {
        this.grupoDDA0002R1PagdrProprio = value;
    }

    /**
     * {@inheritDoc}
     * 
     * @see br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.sspb.recebimento.ConteudoMsgRecebida#getIdMensagemOrigem()
     */
    public Long getIdMensagemOrigem() {
        return null;
    }

    /**
     * {@inheritDoc}
     * 
     * @see br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.sspb.recebimento.ConteudoMsgRecebida#getCodMsg()
     */
    public String getCodMsg() {
        return TipoMensagemDDA.DDA0002R1;
    }

    /**
     * {@inheritDoc}
     * 
     * @see br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.sspb.recebimento.ConteudoMsgRecebida#getNumIdent()
     */
    public Long getNumIdent() {
        return null;
    }

    /*
     * (non-Javadoc)
     * 
     * @see br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.sspb.recebimento.ConteudoMsgRecebida#getNumCtrlDDA()
     */
    public String getNumCtrlDDA() {
        return null;
    }

}
