//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.09 at 09:41:54 AM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.arquivos.ADDA122;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SISARQComplexType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SISARQComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ADDA122" type="{http://www.bcb.gov.br/ARQ/ADDA122.xsd}ADDA122ComplexType"/>
 *         &lt;element name="ADDA122RR2" type="{http://www.bcb.gov.br/ARQ/ADDA122.xsd}ADDA122RR2ComplexType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "SISARQ")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SISARQComplexType", propOrder = { "adda122", "adda122RR2" })
public class SISARQComplexType {

    @XmlElement(name = "ADDA122")
    private ADDA122ComplexType adda122;
    @XmlElement(name = "ADDA122RR2")
    private ADDA122RR2ComplexType adda122RR2;

    public SISARQComplexType() {
    }

    public SISARQComplexType(ADDA122ComplexType adda122) {
        this.adda122 = adda122;
    }

    /**
     * Gets the value of the adda122 property.
     * 
     * @return possible object is {@link ADDA122ComplexType }
     * 
     */
    public ADDA122ComplexType getADDA122() {
        return adda122;
    }

    /**
     * Sets the value of the adda122 property.
     * 
     * @param value allowed object is {@link ADDA122ComplexType }
     * 
     */
    public void setADDA122(ADDA122ComplexType value) {
        this.adda122 = value;
    }

    /**
     * Gets the value of the adda122RR2 property.
     * 
     * @return possible object is {@link ADDA122RR2ComplexType }
     * 
     */
    public ADDA122RR2ComplexType getADDA122RR2() {
        return adda122RR2;
    }

    /**
     * Sets the value of the adda122RR2 property.
     * 
     * @param value allowed object is {@link ADDA122RR2ComplexType }
     * 
     */
    public void setADDA122RR2(ADDA122RR2ComplexType value) {
        this.adda122RR2 = value;
    }

}
