//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 02:22:11 PM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.arquivos.ADDA214;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.arquivos.ADDA214 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can
 * consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods
 * for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.arquivos.ADDA214
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GrupoADDA214MsgComplexType }
     * 
     */
    public GrupoADDA214MsgComplexType createGrupoADDA214MsgComplexType() {
        return new GrupoADDA214MsgComplexType();
    }

    /**
     * Create an instance of {@link GrupoADDA214ArqComplexType }
     * 
     */
    public GrupoADDA214ArqComplexType createGrupoADDA214ArqComplexType() {
        return new GrupoADDA214ArqComplexType();
    }

    /**
     * Create an instance of {@link ADDA214ComplexType }
     * 
     */
    public ADDA214ComplexType createADDA214ComplexType() {
        return new ADDA214ComplexType();
    }

    /**
     * Create an instance of {@link SISARQComplexType }
     * 
     */
    public SISARQComplexType createSISARQComplexType() {
        return new SISARQComplexType();
    }

}
