//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 09:22:27 AM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0106;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for DDA0106ComplexType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DDA0106ComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodMsg" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}CodMsg"/>
 *         &lt;element name="NumCtrlPart" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}ControleIF"/>
 *         &lt;element name="ISPBPartPrincipal" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}ISPB"/>
 *         &lt;element name="ISPBPartAdmtd" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}ISPB"/>
 *         &lt;element name="TpTitConsd" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}TpProprio_Terc" minOccurs="0"/>
 *         &lt;element name="NumIdentcTitInial" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}NumIdentcTit" minOccurs="0"/>
 *         &lt;element name="NumIdentcTitFinl" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}NumIdentcTit" minOccurs="0"/>
 *         &lt;element name="NumRefAtlCadTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}NumRefCad" minOccurs="0"/>
 *         &lt;element name="NumCodBarras" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}NumCodBarras" minOccurs="0"/>
 *         &lt;element name="Grupo_DDA0106_Pagdr" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Grupo_DDA0106_PagdrComplexType" minOccurs="0"/>
 *         &lt;element name="CNPJBase" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}CNPJBase" minOccurs="0"/>
 *         &lt;element name="DtRegHistTit" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DtVencTitIni" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DtVencTitFim" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DtIniCadmntTit" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DtFimCadmntTit" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ISPBPartDestinatario" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}ISPB" minOccurs="0"/>
 *         &lt;element name="SitTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}SitTit" minOccurs="0"/>
 *         &lt;element name="TpRet" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}TpRet"/>
 *         &lt;element name="DtMovto" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DDA0106ComplexType", propOrder = { "codMsg", "numCtrlPart", "ispbPartPrincipal", "ispbPartAdmtd", "tpTitConsd", "numIdentcTitInial", "numIdentcTitFinl",
        "numRefAtlCadTit", "numCodBarras", "grupoDDA0106Pagdr", "cnpjBase", "dtRegHistTit", "dtVencTitIni", "dtVencTitFim", "dtIniCadmntTit", "dtFimCadmntTit",
        "ispbPartDestinatario", "sitTit", "tpRet", "dtMovto" })
public class DDA0106ComplexType {

    @XmlElement(name = "CodMsg", required = true)
    private String codMsg;
    @XmlElement(name = "NumCtrlPart", required = true)
    private String numCtrlPart;
    @XmlElement(name = "ISPBPartPrincipal", required = true)
    private String ispbPartPrincipal;
    @XmlElement(name = "ISPBPartAdmtd", required = true)
    private String ispbPartAdmtd;
    @XmlElement(name = "TpTitConsd")
    private String tpTitConsd;
    @XmlElement(name = "NumIdentcTitInial")
    private BigInteger numIdentcTitInial;
    @XmlElement(name = "NumIdentcTitFinl")
    private BigInteger numIdentcTitFinl;
    @XmlElement(name = "NumRefAtlCadTit")
    private BigInteger numRefAtlCadTit;
    @XmlElement(name = "NumCodBarras")
    private String numCodBarras;
    @XmlElement(name = "Grupo_DDA0106_Pagdr")
    private GrupoDDA0106PagdrComplexType grupoDDA0106Pagdr;
    @XmlElement(name = "CNPJBase")
    private String cnpjBase;
    @XmlElement(name = "DtRegHistTit")
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar dtRegHistTit;
    @XmlElement(name = "DtVencTitIni")
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar dtVencTitIni;
    @XmlElement(name = "DtVencTitFim")
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar dtVencTitFim;
    @XmlElement(name = "DtIniCadmntTit")
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar dtIniCadmntTit;
    @XmlElement(name = "DtFimCadmntTit")
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar dtFimCadmntTit;
    @XmlElement(name = "ISPBPartDestinatario")
    private String ispbPartDestinatario;
    @XmlElement(name = "SitTit")
    private String sitTit;
    @XmlElement(name = "TpRet", required = true)
    private String tpRet;
    @XmlElement(name = "DtMovto", required = true)
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar dtMovto;

    /**
     * Gets the value of the codMsg property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCodMsg() {
        return codMsg;
    }

    /**
     * Sets the value of the codMsg property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCodMsg(String value) {
        this.codMsg = value;
    }

    /**
     * Gets the value of the numCtrlPart property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNumCtrlPart() {
        return numCtrlPart;
    }

    /**
     * Sets the value of the numCtrlPart property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNumCtrlPart(String value) {
        this.numCtrlPart = value;
    }

    /**
     * Gets the value of the ispbPartPrincipal property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getISPBPartPrincipal() {
        return ispbPartPrincipal;
    }

    /**
     * Sets the value of the ispbPartPrincipal property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setISPBPartPrincipal(String value) {
        this.ispbPartPrincipal = value;
    }

    /**
     * Gets the value of the ispbPartAdmtd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getISPBPartAdmtd() {
        return ispbPartAdmtd;
    }

    /**
     * Sets the value of the ispbPartAdmtd property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setISPBPartAdmtd(String value) {
        this.ispbPartAdmtd = value;
    }

    /**
     * Gets the value of the tpTitConsd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTpTitConsd() {
        return tpTitConsd;
    }

    /**
     * Sets the value of the tpTitConsd property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTpTitConsd(String value) {
        this.tpTitConsd = value;
    }

    /**
     * Gets the value of the numIdentcTitInial property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNumIdentcTitInial() {
        return numIdentcTitInial;
    }

    /**
     * Sets the value of the numIdentcTitInial property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setNumIdentcTitInial(BigInteger value) {
        this.numIdentcTitInial = value;
    }

    /**
     * Gets the value of the numIdentcTitFinl property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNumIdentcTitFinl() {
        return numIdentcTitFinl;
    }

    /**
     * Sets the value of the numIdentcTitFinl property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setNumIdentcTitFinl(BigInteger value) {
        this.numIdentcTitFinl = value;
    }

    /**
     * Gets the value of the numRefAtlCadTit property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNumRefAtlCadTit() {
        return numRefAtlCadTit;
    }

    /**
     * Sets the value of the numRefAtlCadTit property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setNumRefAtlCadTit(BigInteger value) {
        this.numRefAtlCadTit = value;
    }

    /**
     * Gets the value of the numCodBarras property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNumCodBarras() {
        return numCodBarras;
    }

    /**
     * Sets the value of the numCodBarras property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNumCodBarras(String value) {
        this.numCodBarras = value;
    }

    /**
     * Gets the value of the grupoDDA0106Pagdr property.
     * 
     * @return possible object is {@link GrupoDDA0106PagdrComplexType }
     * 
     */
    public GrupoDDA0106PagdrComplexType getGrupoDDA0106Pagdr() {
        return grupoDDA0106Pagdr;
    }

    /**
     * Sets the value of the grupoDDA0106Pagdr property.
     * 
     * @param value allowed object is {@link GrupoDDA0106PagdrComplexType }
     * 
     */
    public void setGrupoDDA0106Pagdr(GrupoDDA0106PagdrComplexType value) {
        this.grupoDDA0106Pagdr = value;
    }

    /**
     * Gets the value of the cnpjBase property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCNPJBase() {
        return cnpjBase;
    }

    /**
     * Sets the value of the cnpjBase property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCNPJBase(String value) {
        this.cnpjBase = value;
    }

    /**
     * Gets the value of the dtRegHistTit property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtRegHistTit() {
        return dtRegHistTit;
    }

    /**
     * Sets the value of the dtRegHistTit property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtRegHistTit(XMLGregorianCalendar value) {
        this.dtRegHistTit = value;
    }

    /**
     * Gets the value of the dtVencTitIni property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtVencTitIni() {
        return dtVencTitIni;
    }

    /**
     * Sets the value of the dtVencTitIni property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtVencTitIni(XMLGregorianCalendar value) {
        this.dtVencTitIni = value;
    }

    /**
     * Gets the value of the dtVencTitFim property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtVencTitFim() {
        return dtVencTitFim;
    }

    /**
     * Sets the value of the dtVencTitFim property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtVencTitFim(XMLGregorianCalendar value) {
        this.dtVencTitFim = value;
    }

    /**
     * Gets the value of the dtIniCadmntTit property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtIniCadmntTit() {
        return dtIniCadmntTit;
    }

    /**
     * Sets the value of the dtIniCadmntTit property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtIniCadmntTit(XMLGregorianCalendar value) {
        this.dtIniCadmntTit = value;
    }

    /**
     * Gets the value of the dtFimCadmntTit property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtFimCadmntTit() {
        return dtFimCadmntTit;
    }

    /**
     * Sets the value of the dtFimCadmntTit property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtFimCadmntTit(XMLGregorianCalendar value) {
        this.dtFimCadmntTit = value;
    }

    /**
     * Gets the value of the ispbPartDestinatario property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getISPBPartDestinatario() {
        return ispbPartDestinatario;
    }

    /**
     * Sets the value of the ispbPartDestinatario property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setISPBPartDestinatario(String value) {
        this.ispbPartDestinatario = value;
    }

    /**
     * Gets the value of the sitTit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSitTit() {
        return sitTit;
    }

    /**
     * Sets the value of the sitTit property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSitTit(String value) {
        this.sitTit = value;
    }

    /**
     * Gets the value of the tpRet property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTpRet() {
        return tpRet;
    }

    /**
     * Sets the value of the tpRet property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTpRet(String value) {
        this.tpRet = value;
    }

    /**
     * Gets the value of the dtMovto property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtMovto() {
        return dtMovto;
    }

    /**
     * Sets the value of the dtMovto property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtMovto(XMLGregorianCalendar value) {
        this.dtMovto = value;
    }

}
