//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 09:22:27 AM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.DDA0106;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import br.com.sicoob.sisbr.sicoobdda.comum.negocio.util.ObjectUtil;
import br.com.sicoob.sisbr.sicoobdda.entidades.TipoMensagemDDA;
import br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.sspb.recebimento.ConteudoMsgRecebida;

/**
 * <p>
 * Java class for Grupo_DDA0106R1_TitComplexType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grupo_DDA0106R1_TitComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumIdentcTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}NumIdentcTit"/>
 *         &lt;element name="NumRefAtlCadTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}NumRefCad" minOccurs="0"/>
 *         &lt;element name="NumSeqAtlzCadTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}NumSeqAtlzCadDDA"/>
 *         &lt;element name="ISPBPartDestinatario" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}ISPB"/>
 *         &lt;element name="CodPartDestinatario" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}CodIF" minOccurs="0"/>
 *         &lt;element name="TpPessoaBenfcrioOr" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}TpPessoa"/>
 *         &lt;element name="CNPJ_CPFBenfcrioOr" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}CNPJ_CPF"/>
 *         &lt;element name="Nom_RzSocBenfcrioOr" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Nom_RzSoc"/>
 *         &lt;element name="NomFantsBenfcrioOr" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Nome" minOccurs="0"/>
 *         &lt;element name="LogradBenfcrioOr" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}RuaRem" minOccurs="0"/>
 *         &lt;element name="CidBenfcrioOr" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}CidEnd" minOccurs="0"/>
 *         &lt;element name="UFBenfcrioOr" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}UF" minOccurs="0"/>
 *         &lt;element name="CEPBenfcrioOr" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}CEP" minOccurs="0"/>
 *         &lt;element name="TpPessoaBenfcrioFinl" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}TpPessoa" minOccurs="0"/>
 *         &lt;element name="CNPJ_CPFBenfcrioFinl" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}CNPJ_CPF" minOccurs="0"/>
 *         &lt;element name="Nom_RzSocBenfcrioFinl" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Nom_RzSoc" minOccurs="0"/>
 *         &lt;element name="NomFantsBenfcrioFinl" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Nome" minOccurs="0"/>
 *         &lt;element name="TpPessoaPagdr" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}TpPessoa"/>
 *         &lt;element name="CNPJ_CPFPagdr" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}CNPJ_CPF"/>
 *         &lt;element name="Nom_RzSocPagdr" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Nom_RzSoc"/>
 *         &lt;element name="NomFantsPagdr" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Nome" minOccurs="0"/>
 *         &lt;element name="LogradPagdr" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}RuaRem" minOccurs="0"/>
 *         &lt;element name="CidPagdr" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}CidEnd" minOccurs="0"/>
 *         &lt;element name="UFPagdr" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}UF" minOccurs="0"/>
 *         &lt;element name="CEPPagdr" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}CEP" minOccurs="0"/>
 *         &lt;element name="TpIdentcSacdrAvalst" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}TpIdentcSacdrAvalst"/>
 *         &lt;element name="IdentcSacdrAvalst" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}IdentcSacdrAvalst" minOccurs="0"/>
 *         &lt;element name="Nom_RzSocSacdrAvalst" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Nom_RzSoc" minOccurs="0"/>
 *         &lt;element name="CodCartTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}CodCartTit"/>
 *         &lt;element name="CodMoedaCNAB" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}CodMoedaCNAB"/>
 *         &lt;element name="IdentdNossoNum" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}IdentdNossoNum"/>
 *         &lt;element name="NumCodBarras" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}NumCodBarras"/>
 *         &lt;element name="NumLinhaDigtvl" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}NumLinhaDigtvl" minOccurs="0"/>
 *         &lt;element name="DtVencTit" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="VlrTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Valor"/>
 *         &lt;element name="NumDocTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}NumDocTit" minOccurs="0"/>
 *         &lt;element name="CodEspTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}CodEspTit"/>
 *         &lt;element name="DtEmsTit" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="QtdDiaPrott" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}QtdDias" minOccurs="0"/>
 *         &lt;element name="DtLimPgtoTit" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="TpPgtoTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}TpPgtoTit"/>
 *         &lt;element name="NumParcl" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}NumSeqInf" minOccurs="0"/>
 *         &lt;element name="QtdTotParcl" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}QtdParcl" minOccurs="0"/>
 *         &lt;element name="IndrTitNegcd" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Indr"/>
 *         &lt;element name="IndrBloqPgto" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Indr"/>
 *         &lt;element name="IndrPgtoParcl" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Indr"/>
 *         &lt;element name="QtdPgtoParcl" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}QtdParcl" minOccurs="0"/>
 *         &lt;element name="VlrAbattTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Valor"/>
 *         &lt;element name="Grupo_DDA0106R1_JurosTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Grupo_DDA0106R1_JurosTitComplexType" minOccurs="0"/>
 *         &lt;element name="Grupo_DDA0106R1_MultaTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Grupo_DDA0106R1_MultaTitComplexType" minOccurs="0"/>
 *         &lt;element name="Grupo_DDA0106R1_DesctTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Grupo_DDA0106R1_DesctTitComplexType" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="Grupo_DDA0106R1_NotaFis" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Grupo_DDA0106R1_NotaFisComplexType" maxOccurs="30" minOccurs="0"/>
 *         &lt;element name="TpVlr_PercMinTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}TpVlr_Perc" minOccurs="0"/>
 *         &lt;element name="Vlr_PercMinTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Vlr_PercDDA" minOccurs="0"/>
 *         &lt;element name="TpVlr_PercMaxTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}TpVlr_Perc" minOccurs="0"/>
 *         &lt;element name="Vlr_PercMaxTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Vlr_PercDDA" minOccurs="0"/>
 *         &lt;element name="TpModlCalc" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}TpModlCalc"/>
 *         &lt;element name="TpAutcRecbtVlrDivgte" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}TpAutcRecbtVlrDivgte"/>
 *         &lt;element name="Grupo_DDA0106R1_Calc" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Grupo_DDA0106R1_CalcComplexType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TxtInfBenfcrio" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Txt100" maxOccurs="100" minOccurs="0"/>
 *         &lt;element name="NumRefAtlActe" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}NumRefCad" minOccurs="0"/>
 *         &lt;element name="NumSeqAtlzActe" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}NumSeqAtlzCadDDA" minOccurs="0"/>
 *         &lt;element name="IndrActe" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}IndrActe" minOccurs="0"/>
 *         &lt;element name="Grupo_DDA0106R1_Terc" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Grupo_DDA0106R1_TercComplexType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SitTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}SitTit"/>
 *         &lt;element name="DtHrSit" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="QtdPgtoParclRegtd" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}QtdParcl" minOccurs="0"/>
 *         &lt;element name="VlrSldTotAtlPgtoTit" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Valor" minOccurs="0"/>
 *         &lt;element name="SitTitPgto" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}SitTitPgto"/>
 *         &lt;element name="Grupo_DDA0106R1_BaixaOperac" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Grupo_DDA0106R1_BaixaOperacComplexType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Grupo_DDA0106R1_BaixaEft" type="{http://www.bcb.gov.br/SPB/DDA0106.xsd}Grupo_DDA0106R1_BaixaEftComplexType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grupo_DDA0106R1_TitComplexType", propOrder = { "numIdentcTit", "numRefAtlCadTit", "numSeqAtlzCadTit", "ispbPartDestinatario", "codPartDestinatario",
        "tpPessoaBenfcrioOr", "cnpjcpfBenfcrioOr", "nomRzSocBenfcrioOr", "nomFantsBenfcrioOr", "logradBenfcrioOr", "cidBenfcrioOr", "ufBenfcrioOr", "cepBenfcrioOr",
        "tpPessoaBenfcrioFinl", "cnpjcpfBenfcrioFinl", "nomRzSocBenfcrioFinl", "nomFantsBenfcrioFinl", "tpPessoaPagdr", "cnpjcpfPagdr", "nomRzSocPagdr", "nomFantsPagdr",
        "logradPagdr", "cidPagdr", "ufPagdr", "cepPagdr", "tpIdentcSacdrAvalst", "identcSacdrAvalst", "nomRzSocSacdrAvalst", "codCartTit", "codMoedaCNAB", "identdNossoNum",
        "numCodBarras", "numLinhaDigtvl", "dtVencTit", "vlrTit", "numDocTit", "codEspTit", "dtEmsTit", "qtdDiaPrott", "dtLimPgtoTit", "tpPgtoTit", "numParcl", "qtdTotParcl",
        "indrTitNegcd", "indrBloqPgto", "indrPgtoParcl", "qtdPgtoParcl", "vlrAbattTit", "grupoDDA0106R1JurosTit", "grupoDDA0106R1MultaTit", "grupoDDA0106R1DesctTit",
        "grupoDDA0106R1NotaFis", "tpVlrPercMinTit", "vlrPercMinTit", "tpVlrPercMaxTit", "vlrPercMaxTit", "tpModlCalc", "tpAutcRecbtVlrDivgte", "grupoDDA0106R1Calc",
        "txtInfBenfcrio", "numRefAtlActe", "numSeqAtlzActe", "indrActe", "grupoDDA0106R1Terc", "sitTit", "dtHrSit", "qtdPgtoParclRegtd", "vlrSldTotAtlPgtoTit", "sitTitPgto",
        "grupoDDA0106R1BaixaOperac", "grupoDDA0106R1BaixaEft" })
public class GrupoDDA0106R1TitComplexType implements ConteudoMsgRecebida {

    @XmlElement(name = "NumIdentcTit", required = true)
    private BigInteger numIdentcTit;
    @XmlElement(name = "NumRefAtlCadTit")
    private BigInteger numRefAtlCadTit;
    @XmlElement(name = "NumSeqAtlzCadTit", required = true)
    private BigInteger numSeqAtlzCadTit;
    @XmlElement(name = "ISPBPartDestinatario", required = true)
    private String ispbPartDestinatario;
    @XmlElement(name = "CodPartDestinatario")
    private String codPartDestinatario;
    @XmlElement(name = "TpPessoaBenfcrioOr", required = true)
    private String tpPessoaBenfcrioOr;
    @XmlElement(name = "CNPJ_CPFBenfcrioOr", required = true)
    private BigInteger cnpjcpfBenfcrioOr;
    @XmlElement(name = "Nom_RzSocBenfcrioOr", required = true)
    private String nomRzSocBenfcrioOr;
    @XmlElement(name = "NomFantsBenfcrioOr")
    private String nomFantsBenfcrioOr;
    @XmlElement(name = "LogradBenfcrioOr")
    private String logradBenfcrioOr;
    @XmlElement(name = "CidBenfcrioOr")
    private String cidBenfcrioOr;
    @XmlElement(name = "UFBenfcrioOr")
    private String ufBenfcrioOr;
    @XmlElement(name = "CEPBenfcrioOr")
    private BigInteger cepBenfcrioOr;
    @XmlElement(name = "TpPessoaBenfcrioFinl")
    private String tpPessoaBenfcrioFinl;
    @XmlElement(name = "CNPJ_CPFBenfcrioFinl")
    private BigInteger cnpjcpfBenfcrioFinl;
    @XmlElement(name = "Nom_RzSocBenfcrioFinl")
    private String nomRzSocBenfcrioFinl;
    @XmlElement(name = "NomFantsBenfcrioFinl")
    private String nomFantsBenfcrioFinl;
    @XmlElement(name = "TpPessoaPagdr", required = true)
    private String tpPessoaPagdr;
    @XmlElement(name = "CNPJ_CPFPagdr", required = true)
    private BigInteger cnpjcpfPagdr;
    @XmlElement(name = "Nom_RzSocPagdr", required = true)
    private String nomRzSocPagdr;
    @XmlElement(name = "NomFantsPagdr")
    private String nomFantsPagdr;
    @XmlElement(name = "LogradPagdr")
    private String logradPagdr;
    @XmlElement(name = "CidPagdr")
    private String cidPagdr;
    @XmlElement(name = "UFPagdr")
    private String ufPagdr;
    @XmlElement(name = "CEPPagdr")
    private BigInteger cepPagdr;
    @XmlElement(name = "TpIdentcSacdrAvalst", required = true)
    private BigInteger tpIdentcSacdrAvalst;
    @XmlElement(name = "IdentcSacdrAvalst")
    private String identcSacdrAvalst;
    @XmlElement(name = "Nom_RzSocSacdrAvalst")
    private String nomRzSocSacdrAvalst;
    @XmlElement(name = "CodCartTit", required = true)
    private String codCartTit;
    @XmlElement(name = "CodMoedaCNAB", required = true)
    private String codMoedaCNAB;
    @XmlElement(name = "IdentdNossoNum", required = true)
    private String identdNossoNum;
    @XmlElement(name = "NumCodBarras", required = true)
    private String numCodBarras;
    @XmlElement(name = "NumLinhaDigtvl")
    private String numLinhaDigtvl;
    @XmlElement(name = "DtVencTit")
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar dtVencTit;
    @XmlElement(name = "VlrTit", required = true)
    private BigDecimal vlrTit;
    @XmlElement(name = "NumDocTit")
    private String numDocTit;
    @XmlElement(name = "CodEspTit", required = true)
    private String codEspTit;
    @XmlElement(name = "DtEmsTit", required = true)
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar dtEmsTit;
    @XmlElement(name = "QtdDiaPrott")
    private BigInteger qtdDiaPrott;
    @XmlElement(name = "DtLimPgtoTit")
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar dtLimPgtoTit;
    @XmlElement(name = "TpPgtoTit", required = true)
    private BigInteger tpPgtoTit;
    @XmlElement(name = "NumParcl")
    private BigInteger numParcl;
    @XmlElement(name = "QtdTotParcl")
    private BigInteger qtdTotParcl;
    @XmlElement(name = "IndrTitNegcd", required = true)
    private String indrTitNegcd;
    @XmlElement(name = "IndrBloqPgto", required = true)
    private String indrBloqPgto;
    @XmlElement(name = "IndrPgtoParcl", required = true)
    private String indrPgtoParcl;
    @XmlElement(name = "QtdPgtoParcl")
    private BigInteger qtdPgtoParcl;
    @XmlElement(name = "VlrAbattTit", required = true)
    private BigDecimal vlrAbattTit;
    @XmlElement(name = "Grupo_DDA0106R1_JurosTit")
    private GrupoDDA0106R1JurosTitComplexType grupoDDA0106R1JurosTit;
    @XmlElement(name = "Grupo_DDA0106R1_MultaTit")
    private GrupoDDA0106R1MultaTitComplexType grupoDDA0106R1MultaTit;
    @XmlElement(name = "Grupo_DDA0106R1_DesctTit")
    private List<GrupoDDA0106R1DesctTitComplexType> grupoDDA0106R1DesctTit;
    @XmlElement(name = "Grupo_DDA0106R1_NotaFis")
    private List<GrupoDDA0106R1NotaFisComplexType> grupoDDA0106R1NotaFis;
    @XmlElement(name = "TpVlr_PercMinTit")
    private String tpVlrPercMinTit;
    @XmlElement(name = "Vlr_PercMinTit")
    private BigDecimal vlrPercMinTit;
    @XmlElement(name = "TpVlr_PercMaxTit")
    private String tpVlrPercMaxTit;
    @XmlElement(name = "Vlr_PercMaxTit")
    private BigDecimal vlrPercMaxTit;
    @XmlElement(name = "TpModlCalc", required = true)
    private String tpModlCalc;
    @XmlElement(name = "TpAutcRecbtVlrDivgte", required = true)
    private String tpAutcRecbtVlrDivgte;
    @XmlElement(name = "Grupo_DDA0106R1_Calc")
    private List<GrupoDDA0106R1CalcComplexType> grupoDDA0106R1Calc;
    @XmlElement(name = "TxtInfBenfcrio")
    private List<String> txtInfBenfcrio;
    @XmlElement(name = "NumRefAtlActe")
    private BigInteger numRefAtlActe;
    @XmlElement(name = "NumSeqAtlzActe")
    private BigInteger numSeqAtlzActe;
    @XmlElement(name = "IndrActe")
    private String indrActe;
    @XmlElement(name = "Grupo_DDA0106R1_Terc")
    private List<GrupoDDA0106R1TercComplexType> grupoDDA0106R1Terc;
    @XmlElement(name = "SitTit", required = true)
    private String sitTit;
    @XmlElement(name = "DtHrSit", required = true)
    @XmlSchemaType(name = "dateTime")
    private XMLGregorianCalendar dtHrSit;
    @XmlElement(name = "QtdPgtoParclRegtd")
    private BigInteger qtdPgtoParclRegtd;
    @XmlElement(name = "VlrSldTotAtlPgtoTit")
    private BigDecimal vlrSldTotAtlPgtoTit;
    @XmlElement(name = "SitTitPgto", required = true)
    private String sitTitPgto;
    @XmlElement(name = "Grupo_DDA0106R1_BaixaOperac")
    private List<GrupoDDA0106R1BaixaOperacComplexType> grupoDDA0106R1BaixaOperac;
    @XmlElement(name = "Grupo_DDA0106R1_BaixaEft")
    private List<GrupoDDA0106R1BaixaEftComplexType> grupoDDA0106R1BaixaEft;

    /**
     * Gets the value of the numIdentcTit property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNumIdentcTit() {
        return numIdentcTit;
    }

    /**
     * Sets the value of the numIdentcTit property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setNumIdentcTit(BigInteger value) {
        this.numIdentcTit = value;
    }

    /**
     * Gets the value of the numRefAtlCadTit property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNumRefAtlCadTit() {
        return numRefAtlCadTit;
    }

    /**
     * Sets the value of the numRefAtlCadTit property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setNumRefAtlCadTit(BigInteger value) {
        this.numRefAtlCadTit = value;
    }

    /**
     * Gets the value of the numSeqAtlzCadTit property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNumSeqAtlzCadTit() {
        return numSeqAtlzCadTit;
    }

    /**
     * Sets the value of the numSeqAtlzCadTit property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setNumSeqAtlzCadTit(BigInteger value) {
        this.numSeqAtlzCadTit = value;
    }

    /**
     * Gets the value of the ispbPartDestinatario property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getISPBPartDestinatario() {
        return ispbPartDestinatario;
    }

    /**
     * Sets the value of the ispbPartDestinatario property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setISPBPartDestinatario(String value) {
        this.ispbPartDestinatario = value;
    }

    /**
     * Gets the value of the codPartDestinatario property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCodPartDestinatario() {
        return codPartDestinatario;
    }

    /**
     * Sets the value of the codPartDestinatario property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCodPartDestinatario(String value) {
        this.codPartDestinatario = value;
    }

    /**
     * Gets the value of the tpPessoaBenfcrioOr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTpPessoaBenfcrioOr() {
        return tpPessoaBenfcrioOr;
    }

    /**
     * Sets the value of the tpPessoaBenfcrioOr property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTpPessoaBenfcrioOr(String value) {
        this.tpPessoaBenfcrioOr = value;
    }

    /**
     * Gets the value of the cnpjcpfBenfcrioOr property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getCNPJCPFBenfcrioOr() {
        return cnpjcpfBenfcrioOr;
    }

    /**
     * Sets the value of the cnpjcpfBenfcrioOr property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setCNPJCPFBenfcrioOr(BigInteger value) {
        this.cnpjcpfBenfcrioOr = value;
    }

    /**
     * Gets the value of the nomRzSocBenfcrioOr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNomRzSocBenfcrioOr() {
        return nomRzSocBenfcrioOr;
    }

    /**
     * Sets the value of the nomRzSocBenfcrioOr property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNomRzSocBenfcrioOr(String value) {
        this.nomRzSocBenfcrioOr = value;
    }

    /**
     * Gets the value of the nomFantsBenfcrioOr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNomFantsBenfcrioOr() {
        return nomFantsBenfcrioOr;
    }

    /**
     * Sets the value of the nomFantsBenfcrioOr property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNomFantsBenfcrioOr(String value) {
        this.nomFantsBenfcrioOr = value;
    }

    /**
     * Gets the value of the logradBenfcrioOr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLogradBenfcrioOr() {
        return logradBenfcrioOr;
    }

    /**
     * Sets the value of the logradBenfcrioOr property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLogradBenfcrioOr(String value) {
        this.logradBenfcrioOr = value;
    }

    /**
     * Gets the value of the cidBenfcrioOr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCidBenfcrioOr() {
        return cidBenfcrioOr;
    }

    /**
     * Sets the value of the cidBenfcrioOr property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCidBenfcrioOr(String value) {
        this.cidBenfcrioOr = value;
    }

    /**
     * Gets the value of the ufBenfcrioOr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUFBenfcrioOr() {
        return ufBenfcrioOr;
    }

    /**
     * Sets the value of the ufBenfcrioOr property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setUFBenfcrioOr(String value) {
        this.ufBenfcrioOr = value;
    }

    /**
     * Gets the value of the cepBenfcrioOr property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getCEPBenfcrioOr() {
        return cepBenfcrioOr;
    }

    /**
     * Sets the value of the cepBenfcrioOr property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setCEPBenfcrioOr(BigInteger value) {
        this.cepBenfcrioOr = value;
    }

    /**
     * Gets the value of the tpPessoaBenfcrioFinl property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTpPessoaBenfcrioFinl() {
        return tpPessoaBenfcrioFinl;
    }

    /**
     * Sets the value of the tpPessoaBenfcrioFinl property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTpPessoaBenfcrioFinl(String value) {
        this.tpPessoaBenfcrioFinl = value;
    }

    /**
     * Gets the value of the cnpjcpfBenfcrioFinl property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getCNPJCPFBenfcrioFinl() {
        return cnpjcpfBenfcrioFinl;
    }

    /**
     * Sets the value of the cnpjcpfBenfcrioFinl property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setCNPJCPFBenfcrioFinl(BigInteger value) {
        this.cnpjcpfBenfcrioFinl = value;
    }

    /**
     * Gets the value of the nomRzSocBenfcrioFinl property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNomRzSocBenfcrioFinl() {
        return nomRzSocBenfcrioFinl;
    }

    /**
     * Sets the value of the nomRzSocBenfcrioFinl property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNomRzSocBenfcrioFinl(String value) {
        this.nomRzSocBenfcrioFinl = value;
    }

    /**
     * Gets the value of the nomFantsBenfcrioFinl property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNomFantsBenfcrioFinl() {
        return nomFantsBenfcrioFinl;
    }

    /**
     * Sets the value of the nomFantsBenfcrioFinl property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNomFantsBenfcrioFinl(String value) {
        this.nomFantsBenfcrioFinl = value;
    }

    /**
     * Gets the value of the tpPessoaPagdr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTpPessoaPagdr() {
        return tpPessoaPagdr;
    }

    /**
     * Sets the value of the tpPessoaPagdr property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTpPessoaPagdr(String value) {
        this.tpPessoaPagdr = value;
    }

    /**
     * Gets the value of the cnpjcpfPagdr property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getCNPJCPFPagdr() {
        return cnpjcpfPagdr;
    }

    /**
     * Sets the value of the cnpjcpfPagdr property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setCNPJCPFPagdr(BigInteger value) {
        this.cnpjcpfPagdr = value;
    }

    /**
     * Gets the value of the nomRzSocPagdr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNomRzSocPagdr() {
        return nomRzSocPagdr;
    }

    /**
     * Sets the value of the nomRzSocPagdr property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNomRzSocPagdr(String value) {
        this.nomRzSocPagdr = value;
    }

    /**
     * Gets the value of the nomFantsPagdr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNomFantsPagdr() {
        return nomFantsPagdr;
    }

    /**
     * Sets the value of the nomFantsPagdr property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNomFantsPagdr(String value) {
        this.nomFantsPagdr = value;
    }

    /**
     * Gets the value of the logradPagdr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLogradPagdr() {
        return logradPagdr;
    }

    /**
     * Sets the value of the logradPagdr property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLogradPagdr(String value) {
        this.logradPagdr = value;
    }

    /**
     * Gets the value of the cidPagdr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCidPagdr() {
        return cidPagdr;
    }

    /**
     * Sets the value of the cidPagdr property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCidPagdr(String value) {
        this.cidPagdr = value;
    }

    /**
     * Gets the value of the ufPagdr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUFPagdr() {
        return ufPagdr;
    }

    /**
     * Sets the value of the ufPagdr property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setUFPagdr(String value) {
        this.ufPagdr = value;
    }

    /**
     * Gets the value of the cepPagdr property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getCEPPagdr() {
        return cepPagdr;
    }

    /**
     * Sets the value of the cepPagdr property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setCEPPagdr(BigInteger value) {
        this.cepPagdr = value;
    }

    /**
     * Gets the value of the tpIdentcSacdrAvalst property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getTpIdentcSacdrAvalst() {
        return tpIdentcSacdrAvalst;
    }

    /**
     * Sets the value of the tpIdentcSacdrAvalst property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setTpIdentcSacdrAvalst(BigInteger value) {
        this.tpIdentcSacdrAvalst = value;
    }

    /**
     * Gets the value of the identcSacdrAvalst property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIdentcSacdrAvalst() {
        return identcSacdrAvalst;
    }

    /**
     * Sets the value of the identcSacdrAvalst property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIdentcSacdrAvalst(String value) {
        this.identcSacdrAvalst = value;
    }

    /**
     * Gets the value of the nomRzSocSacdrAvalst property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNomRzSocSacdrAvalst() {
        return nomRzSocSacdrAvalst;
    }

    /**
     * Sets the value of the nomRzSocSacdrAvalst property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNomRzSocSacdrAvalst(String value) {
        this.nomRzSocSacdrAvalst = value;
    }

    /**
     * Gets the value of the codCartTit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCodCartTit() {
        return codCartTit;
    }

    /**
     * Sets the value of the codCartTit property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCodCartTit(String value) {
        this.codCartTit = value;
    }

    /**
     * Gets the value of the codMoedaCNAB property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCodMoedaCNAB() {
        return codMoedaCNAB;
    }

    /**
     * Sets the value of the codMoedaCNAB property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCodMoedaCNAB(String value) {
        this.codMoedaCNAB = value;
    }

    /**
     * Gets the value of the identdNossoNum property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIdentdNossoNum() {
        return identdNossoNum;
    }

    /**
     * Sets the value of the identdNossoNum property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIdentdNossoNum(String value) {
        this.identdNossoNum = value;
    }

    /**
     * Gets the value of the numCodBarras property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNumCodBarras() {
        return numCodBarras;
    }

    /**
     * Sets the value of the numCodBarras property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNumCodBarras(String value) {
        this.numCodBarras = value;
    }

    /**
     * Gets the value of the numLinhaDigtvl property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNumLinhaDigtvl() {
        return numLinhaDigtvl;
    }

    /**
     * Sets the value of the numLinhaDigtvl property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNumLinhaDigtvl(String value) {
        this.numLinhaDigtvl = value;
    }

    /**
     * Gets the value of the dtVencTit property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtVencTit() {
        return dtVencTit;
    }

    /**
     * Sets the value of the dtVencTit property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtVencTit(XMLGregorianCalendar value) {
        this.dtVencTit = value;
    }

    /**
     * Gets the value of the vlrTit property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getVlrTit() {
        return vlrTit;
    }

    /**
     * Sets the value of the vlrTit property.
     * 
     * @param value allowed object is {@link BigDecimal }
     * 
     */
    public void setVlrTit(BigDecimal value) {
        this.vlrTit = value;
    }

    /**
     * Gets the value of the numDocTit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNumDocTit() {
        return numDocTit;
    }

    /**
     * Sets the value of the numDocTit property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNumDocTit(String value) {
        this.numDocTit = value;
    }

    /**
     * Gets the value of the codEspTit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCodEspTit() {
        return codEspTit;
    }

    /**
     * Sets the value of the codEspTit property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCodEspTit(String value) {
        this.codEspTit = value;
    }

    /**
     * Gets the value of the dtEmsTit property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtEmsTit() {
        return dtEmsTit;
    }

    /**
     * Sets the value of the dtEmsTit property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtEmsTit(XMLGregorianCalendar value) {
        this.dtEmsTit = value;
    }

    /**
     * Gets the value of the qtdDiaPrott property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getQtdDiaPrott() {
        return qtdDiaPrott;
    }

    /**
     * Sets the value of the qtdDiaPrott property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setQtdDiaPrott(BigInteger value) {
        this.qtdDiaPrott = value;
    }

    /**
     * Gets the value of the dtLimPgtoTit property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtLimPgtoTit() {
        return dtLimPgtoTit;
    }

    /**
     * Sets the value of the dtLimPgtoTit property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtLimPgtoTit(XMLGregorianCalendar value) {
        this.dtLimPgtoTit = value;
    }

    /**
     * Gets the value of the tpPgtoTit property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getTpPgtoTit() {
        return tpPgtoTit;
    }

    /**
     * Sets the value of the tpPgtoTit property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setTpPgtoTit(BigInteger value) {
        this.tpPgtoTit = value;
    }

    /**
     * Gets the value of the numParcl property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNumParcl() {
        return numParcl;
    }

    /**
     * Sets the value of the numParcl property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setNumParcl(BigInteger value) {
        this.numParcl = value;
    }

    /**
     * Gets the value of the qtdTotParcl property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getQtdTotParcl() {
        return qtdTotParcl;
    }

    /**
     * Sets the value of the qtdTotParcl property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setQtdTotParcl(BigInteger value) {
        this.qtdTotParcl = value;
    }

    /**
     * Gets the value of the indrTitNegcd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIndrTitNegcd() {
        return indrTitNegcd;
    }

    /**
     * Sets the value of the indrTitNegcd property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIndrTitNegcd(String value) {
        this.indrTitNegcd = value;
    }

    /**
     * Gets the value of the indrBloqPgto property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIndrBloqPgto() {
        return indrBloqPgto;
    }

    /**
     * Sets the value of the indrBloqPgto property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIndrBloqPgto(String value) {
        this.indrBloqPgto = value;
    }

    /**
     * Gets the value of the indrPgtoParcl property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIndrPgtoParcl() {
        return indrPgtoParcl;
    }

    /**
     * Sets the value of the indrPgtoParcl property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIndrPgtoParcl(String value) {
        this.indrPgtoParcl = value;
    }

    /**
     * Gets the value of the qtdPgtoParcl property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getQtdPgtoParcl() {
        return qtdPgtoParcl;
    }

    /**
     * Sets the value of the qtdPgtoParcl property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setQtdPgtoParcl(BigInteger value) {
        this.qtdPgtoParcl = value;
    }

    /**
     * Gets the value of the vlrAbattTit property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getVlrAbattTit() {
        return vlrAbattTit;
    }

    /**
     * Sets the value of the vlrAbattTit property.
     * 
     * @param value allowed object is {@link BigDecimal }
     * 
     */
    public void setVlrAbattTit(BigDecimal value) {
        this.vlrAbattTit = value;
    }

    /**
     * Gets the value of the grupoDDA0106R1JurosTit property.
     * 
     * @return possible object is {@link GrupoDDA0106R1JurosTitComplexType }
     * 
     */
    public GrupoDDA0106R1JurosTitComplexType getGrupoDDA0106R1JurosTit() {
        return grupoDDA0106R1JurosTit;
    }

    /**
     * Sets the value of the grupoDDA0106R1JurosTit property.
     * 
     * @param value allowed object is {@link GrupoDDA0106R1JurosTitComplexType }
     * 
     */
    public void setGrupoDDA0106R1JurosTit(GrupoDDA0106R1JurosTitComplexType value) {
        this.grupoDDA0106R1JurosTit = value;
    }

    /**
     * Gets the value of the grupoDDA0106R1MultaTit property.
     * 
     * @return possible object is {@link GrupoDDA0106R1MultaTitComplexType }
     * 
     */
    public GrupoDDA0106R1MultaTitComplexType getGrupoDDA0106R1MultaTit() {
        return grupoDDA0106R1MultaTit;
    }

    /**
     * Sets the value of the grupoDDA0106R1MultaTit property.
     * 
     * @param value allowed object is {@link GrupoDDA0106R1MultaTitComplexType }
     * 
     */
    public void setGrupoDDA0106R1MultaTit(GrupoDDA0106R1MultaTitComplexType value) {
        this.grupoDDA0106R1MultaTit = value;
    }

    /**
     * Gets the value of the grupoDDA0106R1DesctTit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the grupoDDA0106R1DesctTit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getGrupoDDA0106R1DesctTit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link GrupoDDA0106R1DesctTitComplexType }
     * 
     * 
     */
    public List<GrupoDDA0106R1DesctTitComplexType> getGrupoDDA0106R1DesctTit() {
        if (grupoDDA0106R1DesctTit == null) {
            grupoDDA0106R1DesctTit = new ArrayList<GrupoDDA0106R1DesctTitComplexType>();
        }
        return this.grupoDDA0106R1DesctTit;
    }

    /**
     * Gets the value of the grupoDDA0106R1NotaFis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the grupoDDA0106R1NotaFis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getGrupoDDA0106R1NotaFis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link GrupoDDA0106R1NotaFisComplexType }
     * 
     * 
     */
    public List<GrupoDDA0106R1NotaFisComplexType> getGrupoDDA0106R1NotaFis() {
        if (grupoDDA0106R1NotaFis == null) {
            grupoDDA0106R1NotaFis = new ArrayList<GrupoDDA0106R1NotaFisComplexType>();
        }
        return this.grupoDDA0106R1NotaFis;
    }

    /**
     * Gets the value of the tpVlrPercMinTit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTpVlrPercMinTit() {
        return tpVlrPercMinTit;
    }

    /**
     * Sets the value of the tpVlrPercMinTit property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTpVlrPercMinTit(String value) {
        this.tpVlrPercMinTit = value;
    }

    /**
     * Gets the value of the vlrPercMinTit property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getVlrPercMinTit() {
        return vlrPercMinTit;
    }

    /**
     * Sets the value of the vlrPercMinTit property.
     * 
     * @param value allowed object is {@link BigDecimal }
     * 
     */
    public void setVlrPercMinTit(BigDecimal value) {
        this.vlrPercMinTit = value;
    }

    /**
     * Gets the value of the tpVlrPercMaxTit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTpVlrPercMaxTit() {
        return tpVlrPercMaxTit;
    }

    /**
     * Sets the value of the tpVlrPercMaxTit property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTpVlrPercMaxTit(String value) {
        this.tpVlrPercMaxTit = value;
    }

    /**
     * Gets the value of the vlrPercMaxTit property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getVlrPercMaxTit() {
        return vlrPercMaxTit;
    }

    /**
     * Sets the value of the vlrPercMaxTit property.
     * 
     * @param value allowed object is {@link BigDecimal }
     * 
     */
    public void setVlrPercMaxTit(BigDecimal value) {
        this.vlrPercMaxTit = value;
    }

    /**
     * Gets the value of the tpModlCalc property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTpModlCalc() {
        return tpModlCalc;
    }

    /**
     * Sets the value of the tpModlCalc property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTpModlCalc(String value) {
        this.tpModlCalc = value;
    }

    /**
     * Gets the value of the tpAutcRecbtVlrDivgte property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTpAutcRecbtVlrDivgte() {
        return tpAutcRecbtVlrDivgte;
    }

    /**
     * Sets the value of the tpAutcRecbtVlrDivgte property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTpAutcRecbtVlrDivgte(String value) {
        this.tpAutcRecbtVlrDivgte = value;
    }

    /**
     * Gets the value of the grupoDDA0106R1Calc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the grupoDDA0106R1Calc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getGrupoDDA0106R1Calc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link GrupoDDA0106R1CalcComplexType }
     * 
     * 
     */
    public List<GrupoDDA0106R1CalcComplexType> getGrupoDDA0106R1Calc() {
        if (grupoDDA0106R1Calc == null) {
            grupoDDA0106R1Calc = new ArrayList<GrupoDDA0106R1CalcComplexType>();
        }
        return this.grupoDDA0106R1Calc;
    }

    /**
     * Gets the value of the txtInfBenfcrio property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the txtInfBenfcrio property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getTxtInfBenfcrio().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getTxtInfBenfcrio() {
        if (txtInfBenfcrio == null) {
            txtInfBenfcrio = new ArrayList<String>();
        }
        return this.txtInfBenfcrio;
    }

    /**
     * Gets the value of the numRefAtlActe property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNumRefAtlActe() {
        return numRefAtlActe;
    }

    /**
     * Sets the value of the numRefAtlActe property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setNumRefAtlActe(BigInteger value) {
        this.numRefAtlActe = value;
    }

    /**
     * Gets the value of the numSeqAtlzActe property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNumSeqAtlzActe() {
        return numSeqAtlzActe;
    }

    /**
     * Sets the value of the numSeqAtlzActe property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setNumSeqAtlzActe(BigInteger value) {
        this.numSeqAtlzActe = value;
    }

    /**
     * Gets the value of the indrActe property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIndrActe() {
        return indrActe;
    }

    /**
     * Sets the value of the indrActe property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIndrActe(String value) {
        this.indrActe = value;
    }

    /**
     * Gets the value of the grupoDDA0106R1Terc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the grupoDDA0106R1Terc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getGrupoDDA0106R1Terc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link GrupoDDA0106R1TercComplexType }
     * 
     * 
     */
    public List<GrupoDDA0106R1TercComplexType> getGrupoDDA0106R1Terc() {
        if (grupoDDA0106R1Terc == null) {
            grupoDDA0106R1Terc = new ArrayList<GrupoDDA0106R1TercComplexType>();
        }
        return this.grupoDDA0106R1Terc;
    }

    /**
     * Gets the value of the sitTit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSitTit() {
        return sitTit;
    }

    /**
     * Sets the value of the sitTit property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSitTit(String value) {
        this.sitTit = value;
    }

    /**
     * Gets the value of the dtHrSit property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtHrSit() {
        return dtHrSit;
    }

    /**
     * Sets the value of the dtHrSit property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtHrSit(XMLGregorianCalendar value) {
        this.dtHrSit = value;
    }

    /**
     * Gets the value of the qtdPgtoParclRegtd property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getQtdPgtoParclRegtd() {
        return qtdPgtoParclRegtd;
    }

    /**
     * Sets the value of the qtdPgtoParclRegtd property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setQtdPgtoParclRegtd(BigInteger value) {
        this.qtdPgtoParclRegtd = value;
    }

    /**
     * Gets the value of the vlrSldTotAtlPgtoTit property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getVlrSldTotAtlPgtoTit() {
        return vlrSldTotAtlPgtoTit;
    }

    /**
     * Sets the value of the vlrSldTotAtlPgtoTit property.
     * 
     * @param value allowed object is {@link BigDecimal }
     * 
     */
    public void setVlrSldTotAtlPgtoTit(BigDecimal value) {
        this.vlrSldTotAtlPgtoTit = value;
    }

    /**
     * Gets the value of the sitTitPgto property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSitTitPgto() {
        return sitTitPgto;
    }

    /**
     * Sets the value of the sitTitPgto property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSitTitPgto(String value) {
        this.sitTitPgto = value;
    }

    /**
     * Gets the value of the grupoDDA0106R1BaixaOperac property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the grupoDDA0106R1BaixaOperac property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getGrupoDDA0106R1BaixaOperac().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link GrupoDDA0106R1BaixaOperacComplexType }
     * 
     * 
     */
    public List<GrupoDDA0106R1BaixaOperacComplexType> getGrupoDDA0106R1BaixaOperac() {
        if (grupoDDA0106R1BaixaOperac == null) {
            grupoDDA0106R1BaixaOperac = new ArrayList<GrupoDDA0106R1BaixaOperacComplexType>();
        }
        return this.grupoDDA0106R1BaixaOperac;
    }

    /**
     * Gets the value of the grupoDDA0106R1BaixaEft property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the grupoDDA0106R1BaixaEft property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getGrupoDDA0106R1BaixaEft().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link GrupoDDA0106R1BaixaEftComplexType }
     * 
     * 
     */
    public List<GrupoDDA0106R1BaixaEftComplexType> getGrupoDDA0106R1BaixaEft() {
        if (grupoDDA0106R1BaixaEft == null) {
            grupoDDA0106R1BaixaEft = new ArrayList<GrupoDDA0106R1BaixaEftComplexType>();
        }
        return this.grupoDDA0106R1BaixaEft;
    }

    /**
     * {@inheritDoc}
     * 
     * @see br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.sspb.recebimento.ConteudoMsgRecebida#getIdMensagemOrigem()
     */
    public Long getIdMensagemOrigem() {
        return null;
    }

    /**
     * {@inheritDoc}
     * 
     * @see br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.sspb.recebimento.ConteudoMsgRecebida#getCodMsg()
     */
    public String getCodMsg() {
        return TipoMensagemDDA.DDA0106R1;
    }

    /**
     * {@inheritDoc}
     * 
     * @see br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.sspb.recebimento.ConteudoMsgRecebida#getNumIdent()
     */
    public Long getNumIdent() {
        if (!ObjectUtil.isEmpty(getNumIdentcTit())) {
            return getNumIdentcTit().longValue();
        }
        return null;
    }

    /*
     * (non-Javadoc)
     * 
     * @see br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.sspb.recebimento.ConteudoMsgRecebida#getNumCtrlDDA()
     */
    public String getNumCtrlDDA() {
        return null;
    }
}
