//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.26 at 05:36:56 PM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.arquivos.ADDA003;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ADDA003ComplexType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ADDA003ComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Grupo_ADDA003_PagdrDDA" type="{http://www.bcb.gov.br/ARQ/ADDA003.xsd}Grupo_ADDA003_PagdrDDAComplexType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ADDA003ComplexType", propOrder = { "grupoADDA003PagdrDDA" })
public class ADDA003ComplexType {

    @XmlElement(name = "Grupo_ADDA003_PagdrDDA", required = true)
    private List<GrupoADDA003PagdrDDAComplexType> grupoADDA003PagdrDDA;

    /**
     * Gets the value of the grupoADDA003PagdrDDA property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the grupoADDA003PagdrDDA property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getGrupoADDA003PagdrDDA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link GrupoADDA003PagdrDDAComplexType }
     * 
     * 
     */
    public List<GrupoADDA003PagdrDDAComplexType> getGrupoADDA003PagdrDDA() {
        if (grupoADDA003PagdrDDA == null) {
            grupoADDA003PagdrDDA = new ArrayList<GrupoADDA003PagdrDDAComplexType>();
        }
        return this.grupoADDA003PagdrDDA;
    }

}
