//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.26 at 06:15:24 PM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.arquivos.ADDA005;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Grupo_ADDA005_AgrgdDDAComplexType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grupo_ADDA005_AgrgdDDAComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IndrManutAgrgd" type="{http://www.bcb.gov.br/ARQ/ADDA005.xsd}IndrIE"/>
 *         &lt;element name="TpPessoaAgrgd" type="{http://www.bcb.gov.br/ARQ/ADDA005.xsd}TpPessoa"/>
 *         &lt;element name="CNPJ_CPFAgrgd" type="{http://www.bcb.gov.br/ARQ/ADDA005.xsd}CNPJ_CPF"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grupo_ADDA005_AgrgdDDAComplexType", propOrder = { "indrManutAgrgd", "tpPessoaAgrgd", "cnpjcpfAgrgd" })
public class GrupoADDA005AgrgdDDAComplexType {

    @XmlElement(name = "IndrManutAgrgd", required = true)
    private String indrManutAgrgd;
    @XmlElement(name = "TpPessoaAgrgd", required = true)
    private String tpPessoaAgrgd;
    @XmlElement(name = "CNPJ_CPFAgrgd", required = true)
    private BigInteger cnpjcpfAgrgd;

    /**
     * Gets the value of the indrManutAgrgd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIndrManutAgrgd() {
        return indrManutAgrgd;
    }

    /**
     * Sets the value of the indrManutAgrgd property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIndrManutAgrgd(String value) {
        this.indrManutAgrgd = value;
    }

    /**
     * Gets the value of the tpPessoaAgrgd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTpPessoaAgrgd() {
        return tpPessoaAgrgd;
    }

    /**
     * Sets the value of the tpPessoaAgrgd property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTpPessoaAgrgd(String value) {
        this.tpPessoaAgrgd = value;
    }

    /**
     * Gets the value of the cnpjcpfAgrgd property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getCNPJCPFAgrgd() {
        return cnpjcpfAgrgd;
    }

    /**
     * Sets the value of the cnpjcpfAgrgd property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setCNPJCPFAgrgd(BigInteger value) {
        this.cnpjcpfAgrgd = value;
    }

}
