//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 10:01:46 AM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.GEN0014;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import br.com.sicoob.sisbr.sicoobdda.comum.negocio.util.ObjectUtil;
import br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.sspb.recebimento.ConteudoMsgRecebida;

/**
 * <p>
 * Java class for GEN0014R1ComplexType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GEN0014R1ComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodMsg" type="{http://www.bcb.gov.br/GEN/GEN0014.xsd}CodMsg"/>
 *         &lt;element name="NumCtrlIF" type="{http://www.bcb.gov.br/GEN/GEN0014.xsd}ControleIF"/>
 *         &lt;element name="NumCtrlReqIF" type="{http://www.bcb.gov.br/GEN/GEN0014.xsd}ControleIF"/>
 *         &lt;element name="ISPBIF" type="{http://www.bcb.gov.br/GEN/GEN0014.xsd}ISPB"/>
 *         &lt;element name="DtHrIF" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DtMovto" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GEN0014R1ComplexType", propOrder = { "codMsg", "numCtrlIF", "numCtrlReqIF", "ispbif", "dtHrIF", "dtMovto" })
public class GEN0014R1ComplexType implements ConteudoMsgRecebida {

    @XmlElement(name = "CodMsg", required = true)
    private String codMsg;
    @XmlElement(name = "NumCtrlIF", required = true)
    private String numCtrlIF;
    @XmlElement(name = "NumCtrlReqIF", required = true)
    private String numCtrlReqIF;
    @XmlElement(name = "ISPBIF", required = true)
    private String ispbif;
    @XmlElement(name = "DtHrIF", required = true)
    @XmlSchemaType(name = "dateTime")
    private XMLGregorianCalendar dtHrIF;
    @XmlElement(name = "DtMovto", required = true)
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar dtMovto;

    /**
     * Gets the value of the codMsg property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCodMsg() {
        return codMsg;
    }

    /**
     * Sets the value of the codMsg property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCodMsg(String value) {
        this.codMsg = value;
    }

    /**
     * Gets the value of the numCtrlIF property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNumCtrlIF() {
        return numCtrlIF;
    }

    /**
     * Sets the value of the numCtrlIF property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNumCtrlIF(String value) {
        this.numCtrlIF = value;
    }

    /**
     * Gets the value of the numCtrlReqIF property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNumCtrlReqIF() {
        return numCtrlReqIF;
    }

    /**
     * Sets the value of the numCtrlReqIF property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNumCtrlReqIF(String value) {
        this.numCtrlReqIF = value;
    }

    /**
     * Gets the value of the ispbif property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getISPBIF() {
        return ispbif;
    }

    /**
     * Sets the value of the ispbif property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setISPBIF(String value) {
        this.ispbif = value;
    }

    /**
     * Gets the value of the dtHrIF property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtHrIF() {
        return dtHrIF;
    }

    /**
     * Sets the value of the dtHrIF property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtHrIF(XMLGregorianCalendar value) {
        this.dtHrIF = value;
    }

    /**
     * Gets the value of the dtMovto property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtMovto() {
        return dtMovto;
    }

    /**
     * Sets the value of the dtMovto property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtMovto(XMLGregorianCalendar value) {
        this.dtMovto = value;
    }

    /*
     * (non-Javadoc)
     * 
     * @see br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.sspb.recebimento.ConteudoMsgRecebida#getIdMensagemOrigem()
     */
    public Long getIdMensagemOrigem() {
        if (!ObjectUtil.isEmpty(getNumCtrlReqIF())) {
            return Long.parseLong(getNumCtrlReqIF());
        }
        return null;
    }

    /**
     * {@inheritDoc}
     * 
     * @see br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.sspb.recebimento.ConteudoMsgRecebida#getNumIdent()
     */
    public Long getNumIdent() {
        return null;
    }

    /*
     * (non-Javadoc)
     * 
     * @see br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.mensagens.sspb.recebimento.ConteudoMsgRecebida#getNumCtrlDDA()
     */
    public String getNumCtrlDDA() {
        return null;
    }
}
