//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.26 at 05:36:55 PM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.arquivos.ADDA002;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for Grupo_ADDA002_PagdrProprioComplexType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grupo_ADDA002_PagdrProprioComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumIdentcPagdr" type="{http://www.bcb.gov.br/ARQ/ADDA002.xsd}NumIdentcPagdr" minOccurs="0"/>
 *         &lt;element name="NumRefAtlCadCliPagdr" type="{http://www.bcb.gov.br/ARQ/ADDA002.xsd}NumRefCad" minOccurs="0"/>
 *         &lt;element name="NumSeqAtlzCadCliPagdr" type="{http://www.bcb.gov.br/ARQ/ADDA002.xsd}NumSeqAtlzCadDDA"/>
 *         &lt;element name="SitCliPagdrPart" type="{http://www.bcb.gov.br/ARQ/ADDA002.xsd}SitCliPagdrPart"/>
 *         &lt;element name="DtHrSitCliPagdrPart" type="{http://www.bcb.gov.br/ARQ/ADDA002.xsd}DataHora"/>
 *         &lt;element name="Grupo_ADDA002_CtCliPagdr" type="{http://www.bcb.gov.br/ARQ/ADDA002.xsd}Grupo_ADDA002_CtCliPagdrComplexType" maxOccurs="unbounded"/>
 *         &lt;element name="Grupo_ADDA002_AgrgdDDA" type="{http://www.bcb.gov.br/ARQ/ADDA002.xsd}Grupo_ADDA002_AgrgdDDAComplexType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grupo_ADDA002_PagdrProprioComplexType", propOrder = { "numIdentcPagdr", "numRefAtlCadCliPagdr", "numSeqAtlzCadCliPagdr", "sitCliPagdrPart", "dtHrSitCliPagdrPart",
        "grupoADDA002CtCliPagdr", "grupoADDA002AgrgdDDA" })
public class GrupoADDA002PagdrProprioComplexType {

    @XmlElement(name = "NumIdentcPagdr")
    private BigInteger numIdentcPagdr;
    @XmlElement(name = "NumRefAtlCadCliPagdr")
    private BigInteger numRefAtlCadCliPagdr;
    @XmlElement(name = "NumSeqAtlzCadCliPagdr", required = true)
    private BigInteger numSeqAtlzCadCliPagdr;
    @XmlElement(name = "SitCliPagdrPart", required = true)
    private String sitCliPagdrPart;
    @XmlElement(name = "DtHrSitCliPagdrPart", required = true)
    private XMLGregorianCalendar dtHrSitCliPagdrPart;
    @XmlElement(name = "Grupo_ADDA002_CtCliPagdr", required = true)
    private List<GrupoADDA002CtCliPagdrComplexType> grupoADDA002CtCliPagdr;
    @XmlElement(name = "Grupo_ADDA002_AgrgdDDA")
    private List<GrupoADDA002AgrgdDDAComplexType> grupoADDA002AgrgdDDA;

    /**
     * Gets the value of the numIdentcPagdr property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNumIdentcPagdr() {
        return numIdentcPagdr;
    }

    /**
     * Sets the value of the numIdentcPagdr property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setNumIdentcPagdr(BigInteger value) {
        this.numIdentcPagdr = value;
    }

    /**
     * Gets the value of the numRefAtlCadCliPagdr property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNumRefAtlCadCliPagdr() {
        return numRefAtlCadCliPagdr;
    }

    /**
     * Sets the value of the numRefAtlCadCliPagdr property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setNumRefAtlCadCliPagdr(BigInteger value) {
        this.numRefAtlCadCliPagdr = value;
    }

    /**
     * Gets the value of the numSeqAtlzCadCliPagdr property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNumSeqAtlzCadCliPagdr() {
        return numSeqAtlzCadCliPagdr;
    }

    /**
     * Sets the value of the numSeqAtlzCadCliPagdr property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setNumSeqAtlzCadCliPagdr(BigInteger value) {
        this.numSeqAtlzCadCliPagdr = value;
    }

    /**
     * Gets the value of the sitCliPagdrPart property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSitCliPagdrPart() {
        return sitCliPagdrPart;
    }

    /**
     * Sets the value of the sitCliPagdrPart property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSitCliPagdrPart(String value) {
        this.sitCliPagdrPart = value;
    }

    /**
     * Gets the value of the dtHrSitCliPagdrPart property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtHrSitCliPagdrPart() {
        return dtHrSitCliPagdrPart;
    }

    /**
     * Sets the value of the dtHrSitCliPagdrPart property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtHrSitCliPagdrPart(XMLGregorianCalendar value) {
        this.dtHrSitCliPagdrPart = value;
    }

    /**
     * Gets the value of the grupoADDA002CtCliPagdr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the grupoADDA002CtCliPagdr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getGrupoADDA002CtCliPagdr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link GrupoADDA002CtCliPagdrComplexType }
     * 
     * 
     */
    public List<GrupoADDA002CtCliPagdrComplexType> getGrupoADDA002CtCliPagdr() {
        if (grupoADDA002CtCliPagdr == null) {
            grupoADDA002CtCliPagdr = new ArrayList<GrupoADDA002CtCliPagdrComplexType>();
        }
        return this.grupoADDA002CtCliPagdr;
    }

    /**
     * Gets the value of the grupoADDA002AgrgdDDA property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the grupoADDA002AgrgdDDA property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getGrupoADDA002AgrgdDDA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link GrupoADDA002AgrgdDDAComplexType }
     * 
     * 
     */
    public List<GrupoADDA002AgrgdDDAComplexType> getGrupoADDA002AgrgdDDA() {
        if (grupoADDA002AgrgdDDA == null) {
            grupoADDA002AgrgdDDA = new ArrayList<GrupoADDA002AgrgdDDAComplexType>();
        }
        return this.grupoADDA002AgrgdDDA;
    }

}
