//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.26 at 05:37:00 PM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.arquivos.ADDA102;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for Grupo_ADDA102RR2_InstcPgtoTitComplexType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grupo_ADDA102RR2_InstcPgtoTitComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DtVencTit" type="{http://www.bcb.gov.br/ARQ/ADDA102.xsd}Data" minOccurs="0"/>
 *         &lt;element name="VlrTit" type="{http://www.bcb.gov.br/ARQ/ADDA102.xsd}Valor"/>
 *         &lt;element name="QtdDiaPrott" type="{http://www.bcb.gov.br/ARQ/ADDA102.xsd}QtdDias" minOccurs="0"/>
 *         &lt;element name="DtLimPgtoTit" type="{http://www.bcb.gov.br/ARQ/ADDA102.xsd}Data" minOccurs="0"/>
 *         &lt;element name="IndrBloqPgto" type="{http://www.bcb.gov.br/ARQ/ADDA102.xsd}Indr"/>
 *         &lt;element name="VlrAbattTit" type="{http://www.bcb.gov.br/ARQ/ADDA102.xsd}Valor"/>
 *         &lt;element name="QtdPgtoParcl" type="{http://www.bcb.gov.br/ARQ/ADDA102.xsd}QtdParcl" minOccurs="0"/>
 *         &lt;element name="TpModlCalc" type="{http://www.bcb.gov.br/ARQ/ADDA102.xsd}TpModlCalc"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grupo_ADDA102RR2_InstcPgtoTitComplexType", propOrder = { "dtVencTit", "vlrTit", "qtdDiaPrott", "dtLimPgtoTit", "indrBloqPgto", "vlrAbattTit", "qtdPgtoParcl",
        "tpModlCalc" })
public class GrupoADDA102RR2InstcPgtoTitComplexType {

    @XmlElement(name = "DtVencTit")
    private XMLGregorianCalendar dtVencTit;
    @XmlElement(name = "VlrTit", required = true)
    private BigDecimal vlrTit;
    @XmlElement(name = "QtdDiaPrott")
    private BigInteger qtdDiaPrott;
    @XmlElement(name = "DtLimPgtoTit")
    private XMLGregorianCalendar dtLimPgtoTit;
    @XmlElement(name = "IndrBloqPgto", required = true)
    private String indrBloqPgto;
    @XmlElement(name = "VlrAbattTit", required = true)
    private BigDecimal vlrAbattTit;
    @XmlElement(name = "QtdPgtoParcl")
    private BigInteger qtdPgtoParcl;
    @XmlElement(name = "TpModlCalc", required = true)
    private String tpModlCalc;

    /**
     * Gets the value of the dtVencTit property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtVencTit() {
        return dtVencTit;
    }

    /**
     * Sets the value of the dtVencTit property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtVencTit(XMLGregorianCalendar value) {
        this.dtVencTit = value;
    }

    /**
     * Gets the value of the vlrTit property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getVlrTit() {
        return vlrTit;
    }

    /**
     * Sets the value of the vlrTit property.
     * 
     * @param value allowed object is {@link BigDecimal }
     * 
     */
    public void setVlrTit(BigDecimal value) {
        this.vlrTit = value;
    }

    /**
     * Gets the value of the qtdDiaPrott property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getQtdDiaPrott() {
        return qtdDiaPrott;
    }

    /**
     * Sets the value of the qtdDiaPrott property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setQtdDiaPrott(BigInteger value) {
        this.qtdDiaPrott = value;
    }

    /**
     * Gets the value of the dtLimPgtoTit property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDtLimPgtoTit() {
        return dtLimPgtoTit;
    }

    /**
     * Sets the value of the dtLimPgtoTit property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDtLimPgtoTit(XMLGregorianCalendar value) {
        this.dtLimPgtoTit = value;
    }

    /**
     * Gets the value of the indrBloqPgto property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIndrBloqPgto() {
        return indrBloqPgto;
    }

    /**
     * Sets the value of the indrBloqPgto property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIndrBloqPgto(String value) {
        this.indrBloqPgto = value;
    }

    /**
     * Gets the value of the vlrAbattTit property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getVlrAbattTit() {
        return vlrAbattTit;
    }

    /**
     * Sets the value of the vlrAbattTit property.
     * 
     * @param value allowed object is {@link BigDecimal }
     * 
     */
    public void setVlrAbattTit(BigDecimal value) {
        this.vlrAbattTit = value;
    }

    /**
     * Gets the value of the qtdPgtoParcl property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getQtdPgtoParcl() {
        return qtdPgtoParcl;
    }

    /**
     * Sets the value of the qtdPgtoParcl property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setQtdPgtoParcl(BigInteger value) {
        this.qtdPgtoParcl = value;
    }

    /**
     * Gets the value of the tpModlCalc property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTpModlCalc() {
        return tpModlCalc;
    }

    /**
     * Sets the value of the tpModlCalc property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTpModlCalc(String value) {
        this.tpModlCalc = value;
    }

}
