//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.26 at 05:37:00 PM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.arquivos.ADDA102;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SISARQComplexType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SISARQComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ADDA102" type="{http://www.bcb.gov.br/ARQ/ADDA102.xsd}ADDA102ComplexType"/>
 *         &lt;element name="ADDA102RR2" type="{http://www.bcb.gov.br/ARQ/ADDA102.xsd}ADDA102RR2ComplexType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "SISARQ")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SISARQComplexType", propOrder = { "adda102", "adda102RR2" })
public class SISARQComplexType {

    @XmlElement(name = "ADDA102")
    private ADDA102ComplexType adda102;
    @XmlElement(name = "ADDA102RR2")
    private ADDA102RR2ComplexType adda102RR2;

    public SISARQComplexType(ADDA102ComplexType adda102) {
        this.adda102 = adda102;
    }

    public SISARQComplexType() {
    }

    /**
     * Gets the value of the adda102 property.
     * 
     * @return possible object is {@link ADDA102ComplexType }
     * 
     */
    public ADDA102ComplexType getADDA102() {
        return adda102;
    }

    /**
     * Sets the value of the adda102 property.
     * 
     * @param value allowed object is {@link ADDA102ComplexType }
     * 
     */
    public void setADDA102(ADDA102ComplexType value) {
        this.adda102 = value;
    }

    /**
     * Gets the value of the adda102RR2 property.
     * 
     * @return possible object is {@link ADDA102RR2ComplexType }
     * 
     */
    public ADDA102RR2ComplexType getADDA102RR2() {
        return adda102RR2;
    }

    /**
     * Sets the value of the adda102RR2 property.
     * 
     * @param value allowed object is {@link ADDA102RR2ComplexType }
     * 
     */
    public void setADDA102RR2(ADDA102RR2ComplexType value) {
        this.adda102RR2 = value;
    }

}
