//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 02:22:02 PM BRST 
//

package br.com.sicoob.sisbr.sicoobdda.integracaocip.xml.modelo.arquivos.ADDA101;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SISARQComplexType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SISARQComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ADDA101" type="{http://www.bcb.gov.br/ARQ/ADDA101.xsd}ADDA101ComplexType"/>
 *         &lt;element name="ADDA101RR2" type="{http://www.bcb.gov.br/ARQ/ADDA101.xsd}ADDA101RR2ComplexType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "SISARQ")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SISARQComplexType", propOrder = { "adda101", "adda101RR2" })
public class SISARQComplexType {

    @XmlElement(name = "ADDA101")
    private ADDA101ComplexType adda101;
    @XmlElement(name = "ADDA101RR2")
    private ADDA101RR2ComplexType adda101RR2;

    public SISARQComplexType(ADDA101ComplexType adda101) {
        this.adda101 = adda101;
    }

    public SISARQComplexType() {
    }

    /**
     * Gets the value of the adda101 property.
     * 
     * @return possible object is {@link ADDA101ComplexType }
     * 
     */
    public ADDA101ComplexType getADDA101() {
        return adda101;
    }

    /**
     * Sets the value of the adda101 property.
     * 
     * @param value allowed object is {@link ADDA101ComplexType }
     * 
     */
    public void setADDA101(ADDA101ComplexType value) {
        this.adda101 = value;
    }

    /**
     * Gets the value of the adda101RR2 property.
     * 
     * @return possible object is {@link ADDA101RR2ComplexType }
     * 
     */
    public ADDA101RR2ComplexType getADDA101RR2() {
        return adda101RR2;
    }

    /**
     * Sets the value of the adda101RR2 property.
     * 
     * @param value allowed object is {@link ADDA101RR2ComplexType }
     * 
     */
    public void setADDA101RR2(ADDA101RR2ComplexType value) {
        this.adda101RR2 = value;
    }

}
